ministryofjustice/check-financial-eligibility

Gemfile, Gemfile.lock, app/models/assessment.rb, app/services/json_schema_validator.rb, db/migrate/20190517092600_enable_pgcrypto_extension.rb, db/migrate/20190517092721_create_assessments.rb, db/schema.rb, public/schemas/assessment_request.json, public/schemas/assessment_response.json, spec/fixtures/assessment_fixture.rb, spec/fixtures/assessment_response_fixture.rb, spec/fixtures/base_assessment_fixture.rb, spec/models/assessment_spec.rb, spec/rails_helper.rb, spec/services/json_assessment_response_validator_spec.rb, spec/services/json_schema_validator_spec.rb
This defines the response from an eligibility check request.
Also included in this PR:
- move the assessment_request schema to public/schemas so that they can be served by an http request
- write a schema for the response for documentation purposes
- a spec to check that the assessment_response schema works
- create a model to record the request and response.  This will be the log of the activity
0e09375
=> AP-443 Define logging and response

app/models/assessment_particulars.rb, app/services/workflow_service/disposable_capital_assessment.rb, app/services/workflow_service/liquid_capital_assessment.rb, app/services/workflow_service/property_assessment.rb, app/services/workflow_service/vehicle_assessment.rb, config/thresholds/8-Apr-2018.yml, config/thresholds/8-Apr-2019.yml, config/thresholds/8-Apr-2020.yml, public/schemas/assessment_request.json, public/schemas/assessment_response.json, spec/fixtures/assessment_request_fixture.rb, spec/fixtures/assessment_response_fixture.rb, spec/services/json_schema_validator_spec.rb, spec/services/workflow_service/disposable_capital_assessment_spec.rb, spec/services/workflow_service/liquid_capital_assessment_spec.rb, spec/services/workflow_service/property_assessment_spec.rb, spec/services/workflow_service/vehicle_assessment_spec.rb
The`WorkflowService::DisposableCapitalAssessment` service calls other services to work out the assessed value of various categories of capital:
- `LiquidCapitalAssessment`
- `PropertyAssessment`
- `VehicleAssessment`
Previously, it was passing the whole `AssessmentParticulars` object to the sub-services and they were updating that object themselves.  This has the disadvantage that if the structure of the `AssessmentParticulars` object changes (which it will), it means that a lot of classes have to be changed.
This PR changes that behaviour so that just a small relevant section of the structure is passed to the sub service, which returns the result for `DisposableCapitalAssessment` to slot into the right place itself.
=> AP-621a - Refactor Assessment services

app/models/assessment_particulars.rb, app/models/dated_struct.rb, app/services/workflow_service/disposable_capital_assessment.rb, app/services/workflow_service/non_liquid_capital_assessment.rb, app/services/workflow_service/pensioner_capital_disregard.rb, app/services/workflow_service/property_assessment.rb, config/thresholds/8-Apr-2018.yml, config/thresholds/8-Apr-2019.yml, config/thresholds/8-Apr-2020.yml, public/schemas/assessment_request.json, public/schemas/assessment_response.json, spec/fixtures/assessment_request_fixture.rb, spec/fixtures/assessment_response_fixture.rb, spec/models/dated_struct_spec.rb, spec/services/json_schema_validator_spec.rb, spec/services/workflow_service/disposable_capital_assessment_spec.rb, spec/services/workflow_service/non_liquid_capital_assessment_spec.rb, spec/services/workflow_service/pensioner_capital_disregard_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-621)
- Changed DatedStruct to output JSON without the intermediary `table:` key that is output by its parent `OpenStruct`
- Added the `NonLiquidCapitalAssessment` service
- Added the pensioner disregard values to the thresholds config files
- Added the `PensionerCapitalDisregard` service
- Added code to the `DisposableCapitalAssessment` service to add up the populate the results and thresholds in the response structure
=> AP-621 (b) non liquid cap, pensioner disregard and populate results in Disposable Capital Assessment

app/controllers/assessments_controller.rb, app/controllers/dependents_controller.rb, app/models/dependent.rb, app/services/base_creation_service.rb, app/services/dependent_creation_service.rb, app/services/dependents_creation_service.rb, app/services/json_schema_validator.rb, spec/factories/dependent_factory.rb, spec/rails_helper.rb, spec/requests/assessments_spec.rb, spec/requests/dependents_spec.rb, spec/services/assessment_creation_service_spec.rb, spec/services/dependents_creation_service_spec.rb, spec/support/request_helpers.rb
This is Stephen's PR https://github.com/ministryofjustice/check-financial-eligibility/pull/23
plus  a refactor of the service like we decided.
I'm also using Rails' `accepts_nested_attributes_for` which is very useful for creating the dependents and incomes in one line without having to use `ActiveRecord::Base.transaction`
=> AP-729 dependent creation refactor

app/controllers/assessments_controller.rb, app/controllers/dependents_controller.rb, app/services/dependent_creation_service.rb, app/services/dependents_creation_service.rb, app/services/json_schema_validator.rb, spec/rails_helper.rb, spec/requests/assessments_spec.rb, spec/requests/dependents_spec.rb, spec/services/assessment_creation_service_spec.rb, spec/services/dependents_creation_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-729)
Refactored the above classes so as to use the same pattern as Julien used for Assessments creation:
- moved the generation of the response and status code from service to controller
- removed links from response
- made stubbing the response from reading the schema into a rspec helper method
=> AP-729 refactor of the dependents creation service

app/controllers/properties_controller.rb, app/services/properties_creation_service.rb, spec/requests/properties_spec.rb, spec/services/properties_creation_service_spec.rb
Refactor the Create Properties Feature
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-731)
I updated the PropertiesCreationService to use the BaseCreationService. 
- Updated the controller to render a json response from the result of the creation service
- Updated tests
=> AP731 Refactor Create Properties

app/controllers/applicants_controller.rb, app/models/applicant.rb, app/models/assessment.rb, app/services/applicant_creation_service.rb, config/routes.rb, db/migrate/20190614123520_create_applicants.rb, db/schema.rb, public/schemas/applicant.json, spec/models/applicant_spec.rb, spec/requests/applicants_spec.rb, spec/services/applicant_creation_service_spec.rb
AP728 Create Applicant for Means Calculation Service
[Create Applicant - Means Calculation Service](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&modal=detail&selectedIssue=AP-728)
Created:  
- Applicants model that belongs_to the Assessment model and each assessment has one applicant.
- ApplicantCreationService that validates the applicant params passed in and if successful creates an applicant and returns self.
- ApplicantsController to call the ApplicationCreationService and render a  json success or error response depending on the result.
- Applicant JSON schema
- Tests
=> AP728 Create Applicant

app/controllers/dependants_controller.rb, app/models/assessment.rb, app/models/dependant.rb, app/models/dependant_income_receipt.rb, app/services/dependants_creation_service.rb, config/routes.rb, db/migrate/20190710105635_change_dependants_spelling.rb, db/schema.rb, public/schemas/dependant.json, public/schemas/vehicles.json, spec/factories/dependant_factory.rb, spec/fixtures/assessment_request.json, spec/fixtures/assessment_response_fixture.rb, spec/models/dependant_income_receipt_spec.rb, spec/models/dependant_spec.rb, spec/requests/dependants_spec.rb, spec/services/dependants_creation_service_spec.rb, spec/services/json_schema_validator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-763)
CheckFinancialEligibility was using the spelling dependent rather than dependant. This changes all uses to the preferred spelling. It also updates the database with a migration.
I used find/replace with case sensitivity to swap the spellings, left everything in the db file untouched and created a new migration file to rename the relevant tables and fields. I then ran `bundle exec rspec` and everything passed.
I was doing this as I was going along in AP-768 but realised that the PR at the end would be enormous and difficult for a reviewer to see what had actually changed so I split this off into its own PR.
=> Change spelling from dependent to dependant

app/services/payment_period_analyser.rb, app/services/time_series_calculator.rb, spec/services/payment_period_analyser_spec.rb, spec/support/salary_pattern_generator.rb
[Jira AP-783](https://dsdmoj.atlassian.net/browse/AP-783)
Generates sets of time series data of various patterns, and passes them to a new service `PaymentPeriodAnalyser` to determine if it can identify the correct period of payment.
The solution works, but struggles to distinguish between monthly and four-weekly series where there is a lot of variance (more than a couple of days) and the sequence of days is negatively sloped (that is, each day is earlier in the month). That is, _[13-May-19, 14-Jun-19, 15-Jul-19]_ is unlikely to be four weekly because each day is higher through the sequence (positively sloped). But _[16-May-19, 14-Jun-19, 12-Jul-19]_ could be either four weekly or monthly with a two day variance.
=> AP-783 Adds PaymentPeriodAnalyser to determine frequency of payment

app/services/workflow_manager.rb, spec/services/workflow_manager_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-817)
Changed workflow manager to:
- accept `assessment_id` rather than JSON struct in initializer
- Call all required services passing in the `Assessment` object rather than the JSON struct
=> AP-817 Convert WorkflowManager to use DB

app/models/benefit_receipt.rb, app/models/concerns/payment_pattern_concern.rb, app/models/wage_slip.rb, app/services/date_slope.rb, app/services/payment_period_analyser.rb, spec/models/benefit_receipt_spec.rb, spec/models/wage_slip_spec.rb, spec/services/date_slope_spec.rb, spec/services/payment_period_analyser_spec.rb
[Jira AP-641](https://dsdmoj.atlassian.net/browse/AP-641)
This adds a `payment_pattern` class method to `BenefitReceipt` and `WageSlip`, together with a `time_series` scope option. With this in place, the payment patterns for an assessment can be determined via:
- `assessment.benefit_receipts.payment_pattern`
- `assessment.wage_slips.payment_pattern`
`payment_pattern` returns one of `:monthly`, `:weekly`, `:two_weekly`, `:four_weekly`, `:unknown` depending on the sequence of payment dates.
Also the slope calculation has been split out from `PaymentPeriodAnalyser` and a system added that allows better analysis of data sequences that straddle the month end. Also constants have been added to `PaymentPeriodAnalyser` to aid adjustment of the values at a later date.
=> AP-641 identify frequency of payments

app/models/assessment.rb, app/models/result.rb, app/services/assessment_creation_service.rb, app/services/base_workflow_service.rb, app/services/workflow_service/liquid_capital_assessment.rb, db/migrate/20190729103203_create_results.rb, db/schema.rb, spec/services/assessment_creation_service_spec.rb, spec/services/workflow_service/liquid_capital_assessment_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-785)
Refactor the `LiquidCapitalAssessment` service to use data from the database and not the JSON struct.
- Accept `assessment_id` rather than JSON struct in `initializer`
- Use the `Assessment` object to retrieve `BankAccount` data
This PR doesn't change the `DisposableCapitalAssessment` service which calls `LiquidCapitalAssessment`. That will be handled in a separate story (AP-784).
=> AP-785 Amend LiquidCapitalAssessment service

app/models/result.rb, app/services/base_workflow_service.rb, app/services/workflow_service/pensioner_capital_disregard.rb, config/thresholds/8-Apr-2019.yml, config/thresholds/8-Apr-2020.yml, db/migrate/20190729100752_create_results.rb, spec/factories/applicant_factory.rb, spec/factories/result_factory.rb, spec/services/date_slope_spec.rb, spec/services/workflow_service/pensioner_capital_disregard_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-787)
Converted the service to use `Assessment` and `Applicant` database records and record result in `Result` database records, rather than the large JSON struct
=> AP-787 Convert Pensioner Disregard service to use database

app/models/dated_struct.rb, app/services/base_workflow_service.rb, app/services/workflow_service/non_liquid_capital_assessment.rb, spec/services/workflow_service/non_liquid_capital_assessment_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-785)
Refactor the `NonLiquidCapitalAssessment` service to use data from the database and not the JSON struct.
- Accept `assessment_id` rather than JSON struct in `initializer`
- Use the `Assessment` object to retrieve `non_liquid_assets` data
This PR doesn't change the DisposableCapitalAssessment service which calls NonLiquidCapitalAssessment. That will be handled in a separate story (AP-784).
=> AP-786 Amend NonLiquidCapitalAssessment service

app/services/base_workflow_service.rb, app/services/workflow_service/property_assessment.rb, spec/factories/property_factory.rb, spec/services/workflow_service/property_assessment_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-788)
This service was written to use values from the original large JSON payload. We have now converted the controllers to store values in database records, so refactor to use the database records and not the JSON struct.
* Accept `assessment` rather than JSON struct in `initializer`
* Use the `Assessment` object to retrieve `property` data
* Refactor tests 
* This PR doesn't change the `DisposableCapitalAssessment` service which calls `PropertyAssessment`. That will be handled in a separate story (AP-784).
=> AP-788 Amend PropertyAssessment service

app/services/base_workflow_service.rb, app/services/workflow_service/vehicle_assessment.rb, spec/factories/assessment_factory.rb, spec/services/workflow_service/vehicle_assessment_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-759)
Refactor the `VehicleAssessment` service to use data from the database and not the JSON struct.
* Accept an `Assessment` instance rather than JSON struct in `initializer`
* Use the `Assessment` object to retrieve `Vehicle` data
* Fix bug in `assessment_factory` by switching to `Faker` to generate IP addresses
=> Ap 789 vehicle assessment service db

spec/factories/bank_account_factory.rb, spec/services/capitals_creation_service_spec.rb
The `capitals_creation_service_spec` randomly fails. This is due to the use of `Faker::Bank.name` to create bank account names. There is only a small pool of bank names to select from so occasionally both accounts are created with the same name, leading to failures when `find_by!(name: bank_account[:name])` is executed.
I've fixed this by adding `Faker::Bank.account_number` to the name created by FactoryBot, which should hopefully result in unique names always being created.
=> Fix failing capital spec

app/workflows/standard_workflow.rb, config/routes.rb, spec/requests/status_spec.rb
K8s deployments to UAT and staging are failing due to
* missing module name. This causes `NameError: uninitialized constant BelowLowerCapitalThresholdPredicate` to be thrown when the server is started. Change `BelowLowerCapitalThresholdPredicate` to `WorkflowPredicate::BelowLowerCapitalThresholdPredicate` to fix this.
* no `status` route. K8s does a `GET` to `/status` to check whether the application is live. `status_controller` exists but has no route. This causes the deployment to fail. Add a route to `routes.rb` to remedy this.
I've tested in UAT and have successfully deployed there, so I assume this will also fix the problem for staging.
=> Fix failing UAT and staging deploys

.circleci/config.yml
Remove erroneous hosts of staging and prod deployment.
We don't need to pass them to the `helm upgrade` because `ingress.hosts` is already set in the `values-*.yml` files
=> Remove wrong host for staging and prod deployment

app/models/capital_summary.rb, spec/models/capital_summary_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-997)
For cases where the applicant has an involvement type of `applicant` and the matter proceeding type is `domestic_abuse`, the upper capital threshold does not apply. All applicants above the lower threshold should have a result of `contribution_required`.
For MVP all cases are `applicant`/`domestic_abuse`, so to change this simply amend the `capital_summary` model to remove the upper threshold.
It can be reinstated when other involvement types/matter types are introduced to the service.
=> AP-997 Remove upper capital threshold

app/models/property.rb, spec/services/workflow_service/property_assessment_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-998)
The capital calculation is incorrect for properties where ownership is shared with a housing association.
In these instances the housing association share is a percentage of the market value rather than a percentage of the net equity.
This PR amends the `calculate_net_equity` method on the `property` model so that the correct value is calculated dependent on whether a housing association owns a share of the property.
A (disabled) spec already existed for this scenario. It has been enabled and updated with correct values derived from the [guidance](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/1339654172/3.+Detailed+Means+Calculation+-+Capital+Assets?preview=/1339654172/1547763935/Property.pdf) in the Jira story. 
It also …
=> AP-998 Fix Property Calculation

app/controllers/assessments_controller.rb, app/models/assessment.rb, app/models/gross_income_summary.rb, app/services/base_workflow_service.rb, app/services/workflow_service/gross_income_collator.rb, config/thresholds/8-Apr-2018.yml, config/thresholds/8-Apr-2019.yml, config/thresholds/8-Apr-2020.yml, db/migrate/20191206141200_add_upper_threshold_to_gross_income_summary.rb, db/schema.rb, spec/factories/assessment_factory.rb, spec/factories/dependant_factory.rb, spec/models/gross_income_summary_spec.rb, spec/requests/assessments_spec.rb, spec/services/workflow_service/gross_income_collator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1103)
Added gross income upper threshold data and a mechanism for deriving the correct threshold.
* new database column on `gross_income_summary` to hold `upper_threshold`.
* new values in `config/thresholds` to hold threshold-related data: 
- `gross_income_upper` - the basic threshold
- `dependant_increase_starts_after` - the number of dependants above which the threshold is increased
- `dependent_step` - the amount each additional dependant adds to the threshold
- `infinite_gross_income_upper` - where the threshold is waived, an 'infinite' threshold applies. This is encoded as £999,999,999,999
* new `GrossIncomeCollator` class to calculate the correct threshold an persist it to the database
NOTE: values for the 2020 gross income …
=> AP-1103 Calculate gross income threshold

app/models/assessment.rb, app/models/assessment_error.rb, app/models/other_income_source.rb, app/services/monthly_other_income_calculator.rb, app/services/payment_period_data_extractor.rb, app/services/unearned_income_monthly_conversion_service.rb, db/migrate/20191205155502_add_other_income_sources.rb, db/migrate/20191205164153_create_other_income_payments.rb, db/migrate/20191209131409_add_monthly_oher_income_to_gross_income_summary.rb, db/migrate/20191210100303_create_assessment_errors.rb, db/migrate/20191210102843_drop_wage_slips.rb, db/migrate/20191211161738_add_fields_to_other_payments.rb, db/schema.rb, spec/factories/gross_income_summary_factory.rb, spec/factories/other_income_payment_factory.rb, spec/factories/other_income_source_factory.rb, spec/models/other_income_source_spec.rb, spec/services/payment_period_data_extractor_spec.rb, spec/services/unearned_income_monthly_conversion_service_spec.rb, spec/support/faker/other_income_source.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1127)
This PR takes care of calcualating the monthly income for each `OtherIncomeSource`, storing it on the `OtherIncomeSource` model, and the total for all sources on the `GrossIncomeSummary` record.  If the monthly income can't be calculated for any reason, e.g. the`PaymentPeriodAnalyser` can't determine the frequency of payments, an `AssessmentError` record is written to provide details.
- Added `AssessmentError` model to record cases and reasons where an assessment can’t be automatically calculated
- Added `OtherIncomeSource` model belonging to `GrossIncomeSummary` to record the various sources of other income
- Added `OtherIncomePayment` model belonging to `OtherIncomeSource` to record payments from each source
- Added …
=> AP-1127 Calculate monthly value for OtherIncome

config/thresholds/8-Apr-2020.yml
Copy the 2019 gross income threshold values to the 2020 config file. 
It's possible they will change, in which case a further PR will be needed, but it's probably better to have some values populated now - if we forget to add them before April 2020 failures will occur.
=> Add 2020 gross income threshold values

db/migrate/20191220091038_add_code_to_state_benefit_types.rb, db/schema.rb, db/seeds.rb, db/seeds/data/state_benefit_types.yml
We now have (a probably incomplete) list of DWP benefits and their codes to add to the list of benfits that are excluded from the means assessment by the LAA.  These new benefit types and their DWP codes have been added to the seeds
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1120)
- Added new field `dwp_code`
=> AP-1120 Update State Benefit Type seeds with DWP codes

app/models/assessment.rb, app/models/disposable_income_summary.rb, db/migrate/20191223132825_create_disposable_income_summaries.rb, db/schema.rb
Create DisposableIncomeSummary model and migration file
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&modal=detail&selectedIssue=AP-1157)
- Create DisposableIncomeSummary model that belongs_to an :assessment
- Add enum housing_cost_type: enum_hash_for(:rent, :mortgage, :board_and_lodging) on the DisposableIncomeSummary model.
- Update the Assessment to have one DisposableIncomeSummary
=> AP1157 DisposableIncomeSummary model and migration file

.rubocop_todo.yml, app/controllers/outgoings_controller.rb, app/models/disposable_income_summary.rb, app/models/outgoings/housing_cost.rb, app/services/creators/base_creator.rb, app/services/creators/capitals_creator.rb, app/services/creators/dependants_creator.rb, app/services/creators/outgoings_creator.rb, app/services/creators/properties_creator.rb, app/services/creators/state_benefits_creator.rb, config/initializers/apipie.rb, db/migrate/20191230112428_create_new_outgoings.rb, db/migrate/20191230141019_remove_housing_cost_type.rb, db/schema.rb, doc/apipie_examples.json, spec/requests/outgoings_spec.rb, spec/services/creators/outgoings_creator_spec.rb
The old `OutgoingsController` and `OutgoingsCreationService` were removed in the previous PR when the database was restructured in order to prevent failing tests.  This implements the new controllers and creation services to manage input int he new format and use the new database structure.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1148)
- Added `Outgoings Controller`
- Added `OutgoingsCreationService`
- Moved the type of housing cost from `DisposableIncomeSummary` record to each individual `Outgoings::HousingCost` records
- Moved the `#assessment` method from individual creation services to `Creators::BaseCreator`
=> AP-1148 Outgoings Controller

app/models/disposable_income_summary.rb, app/services/assessors/gross_income_assessor.rb, app/services/collators/disposable_income_collator.rb, app/services/collators/gross_income_collator.rb, app/services/collators/housing_costs_collator.rb, config/thresholds/8-Apr-2018.yml, config/thresholds/8-Apr-2019.yml, config/thresholds/8-Apr-2020.yml, db/migrate/20200103150316_add_total_gross_income_to_gross_income_summary.rb, db/migrate/20200103151346_rename_cols_on_disposable_income_summary.rb, db/schema.rb, spec/factories/disposable_income_summary_factory.rb, spec/services/assessors/gross_income_assessor_spec.rb, spec/services/collators/childcare_collator_spec.rb, spec/services/collators/disposable_income_collator_spec.rb, spec/services/collators/housing_cost_collator_spec.rb, spec/services/collators/maintenance_collator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1155)
- rename fields on `DisposableIncomeSummary` to remove `monthly_` prefix  - they are all monthly
- Write `Collators::DisposableIncomeCollator` to calculate above fields and populate on dispoable income summary record.
=> AP-1155 Disposable income collator

app/services/calculators/state_benefits_calculator.rb, app/services/collators/gross_income_collator.rb, spec/requests/assessments_spec.rb, spec/services/calculators/state_benefits_calculator_spec.rb
Use StateBenefitsCalculator in GrossIncomeCollator
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1213)
- Change StateBenefitCollator to a calculator (StateBenefitsCalculator)
- Return total_monthly_state_benefits from StateBenefitsCalculator
- Call and use return value of StateBenefitsCalculator in GrossIncomeCollator
- Update tests
=> AP1213 Use StateBenefitsCalculator to calculator total monthly state benefits

.circleci/config.yml
Step 1:
This should make CircleCI auto-deploy PRs if the branch name starts with dependabot
It creates an auto-deploy-uat job and filters it to run for PR's starting with dependabot
Step 2:
Ignore the manual hold and deploy steps for dependabot prefixed branches
Step 3:
Use correct regex for dependabot PR's, they are always `dependabot/bundler/gem_name-version`
##Step two working too
##Step 3
This has correctly reverted to the manual jobs as my branch name does not match the true dependabot branch naming convention
=> FIX: Make CircleCI auto-deploy to UAT

.circleci/config.yml, bin/delete_uat_release.sh
These duplicate the working steps used in apply
It will ignore the hold_ and deploy_uat steps for merges to master,
while running the auto-deploy-uat step instead
I have also implemented the delete_UAT step.  It was defined in the config file, but never called and the bin script was missing.
=> Circle-Update: Add filter to circleci/config

bin/delete_uat_release.sh
## What
This was a copy/paste omission from the apply script
=> FIX: Remove the apply prefix in the delete_uat script

.github/workflows/manual-integration-tests.yml, spec/spec_helper.rb
* Add postgres and configure for the test runs
* Implement a skip_coverage env_var this allows us to run *some* tests without the coverage drop causing the test to "fail"
* configure caching of the bundler set, this speeds up the run 
Triggering the job is via an API call using curl/postman/etc
``` sh
curl -H "Accept: application/vnd.github.everest-preview+json" \
-H "Authorization: token <YOUR PERSONAL ACCESS TOKEN>" \
--request POST \
--data '{"event_type": "manual-trigger"}' \
https://api.github.com/repos/ministryofjustice/check-financial-eligibility/dispatches
```
- implement a google drive link (working on local branch, awaiting central access to google cloud platform for the access key) to pull down new xlsx version of google sheet source
- Configure a call back that monitors the …
=> FIX: Update manual test step

config/thresholds/6-Apr-2020.yml, spec/services/calculators/dependant_allowance_calculator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1348)
AP1348 Update dependant threshold allowances for 6th April
The calculation_date/submission_date is already used for delegated and substantive application calculations.
Update tests.
To note:
The dependant type 'Partner' is not currently used so it is ignored.
=> AP1348 Update dependant threshold allowances for 6th april

app/controllers/other_incomes_controller.rb, app/models/other_income_source.rb, app/services/collators/gross_income_collator.rb, app/services/creators/other_incomes_creator.rb, app/services/decorators/gross_income_summary_decorator.rb, app/services/decorators/monthly_income_equivalent_decorator.rb, db/migrate/20200420132900_add_fields_to_gross_income_summary.rb, db/schema.rb, doc/apipie_examples.json, spec/factories/other_income_source_factory.rb, spec/factories/state_benefit_factory.rb, spec/requests/assessments_spec.rb, spec/requests/other_incomes_spec.rb, spec/services/calculators/state_benefits_calculator_spec.rb, spec/services/collators/childcare_collator_spec.rb, spec/services/collators/gross_income_collator_spec.rb, spec/services/creators/other_incomes_creator_spec.rb, spec/services/decorators/gross_income_summary_decorator_spec.rb, spec/services/decorators/other_income_source_decorator_spec.rb, spec/services/decorators/state_benefit_decorator_spec.rb, spec/services/utilities/payment_period_analyser_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1374)
This PR implements the first part of AP-1374 - that is to include a structure monthly_income_equivalents in the response body.
- Limited types valid types of other income to `friends_or_family`, `maintenance_in`, `property_or_lodger`, `student_loan`, `pension` (or their humanized equivalents)
- Added validation to `OtherIncomeSource` records so that the nae is one of the above values
- Added extra columns to the `GrossIncomeSummary` record to hold the totals for each category
-  Added the extra section into the `GrossIncomeSummaryDecorator` to output the relevant data
=> AP-1374 monthly breakdown

.rubocop.yml, lib/integration_helpers/expected_result.rb, lib/tasks/integration.rake, spec/integration/test_runner_spec.rb
Integration tests can either be run in three modes:
- silent (used in Circle CI testing - just pass if all tests pass, otherwise fail)
- verbose (normal, with results printed for each tests)
- noisy (prints payloads sent and received for each step, as well as detailed results)
The verbose mode is default.
Silent mode is enabled by adding [silent] to the rake task, e.g. 
`rake integration[silent]`
Noisy mode should be enabled by adding noisy to the rake task
`rake integration[noisy]`
There was a bug preventing this from happening.  This PR fixes it.
Also, now prints the name of the worksheet against the results.
=> Fix bug preventing noisy output of integration tests

app/controllers/outgoings_controller.rb, app/models/disposable_income_summary.rb, app/models/outgoings/legal_aid.rb, app/services/collators/legal_aid_collator.rb, app/services/collators/outgoings_collator.rb, app/services/creators/outgoings_creator.rb, app/services/decorators/disposable_income_summary_decorator.rb, app/services/decorators/gross_income_summary_decorator.rb, app/services/decorators/monthly_outgoing_equivalent_decorator.rb, app/services/workflows/non_passported_workflow.rb, db/migrate/20200424071046_add_legal_aid_to_disposable_income_summary.rb, db/schema.rb, doc/apipie_examples.json, spec/factories/disposable_income_summary_factory.rb, spec/factories/outgoing_factory.rb, spec/requests/assessments_spec.rb, spec/requests/outgoings_spec.rb, spec/services/collators/legal_aid_collator_spec.rb, spec/services/collators/outgoings_collator_spec.rb, spec/services/creators/outgoings_creator_spec.rb, spec/services/decorators/disposable_income_summary_decorator_spec.rb, spec/services/decorators/gross_income_summary_decorator_spec.rb, spec/services/workflows/non_passported_workflow_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1381)
- validate the outgoing types to those which Apply will send across (plus deprecated type names used in the integration tests: to be removed once the integration tests have been updated)
- Added `legal_aid` column to the `disposable_income summaries` table
- Added `LegalAidOutgoing` model
- Added `Collators::LegalAidCollator` to summarise legal aid payments
- Added `Decorators::MonthlyOutgoingEquivalentDecorator` to output the new section as json
- Made sure the `Collator::DisposableIncomeCollator` was called even if the applicant was eligible under the gross income test (previously it did this as part of the Disposable income test only if the applicant failed the gross income test)
=> AP-1381 Categorise outgoings in response

README.md, app/models/state_benefit.rb, app/services/calculators/disregarded_state_benefits_calculator.rb, app/services/decorators/deductions_decorator.rb, app/services/decorators/disposable_income_summary_decorator.rb, doc/apipie_examples.json, spec/factories/state_benefit_factory.rb, spec/factories/state_benefit_type_factory.rb, spec/services/calculators/disregarded_state_benefits_calculator_spec.rb, spec/services/decorators/deductions_decorator_spec.rb, spec/services/decorators/disposable_income_summary_decorator_spec.rb, spec/services/decorators/state_benefit_decorator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1382)
adds deductions (dependants_allowance and disregarded_state_benefits) to the disposable_income_summary payload
there is an existing dependants_allowance attribute, this will need to be removed once Apply has been amended to cope with moving it
=> Ap 1382 add deductions to the payload

app/models/assessment.rb, config/initializers/remarks.rb, db/migrate/20200514131226_add_remarks_to_assessment.rb, db/schema.rb, spec/models/assessment_spec.rb, spec/services/remarks_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1401)
- added a column `remarks` to the `assessments` table to hold a serialized `Remarks` class
- Automatically instantiate a new `Remarks` class if the value of that column is nil
- Add an initializer for the `Remarks` class to ensure the class is loaded before the first Assessment
=> AP-1401 adding Remarks to Assessment

app/controllers/assessments_controller.rb, app/controllers/other_incomes_controller.rb, app/controllers/outgoings_controller.rb, app/controllers/state_benefits_controller.rb, app/models/concerns/default_client_id.rb, app/models/other_income_payment.rb, app/models/outgoings/base_outgoing.rb, app/models/state_benefit_payment.rb, app/services/creators/other_incomes_creator.rb, app/services/creators/state_benefits_creator.rb, app/services/decorators/assessment_decorator.rb, db/migrate/20200514152255_add_client_id_to_income_outoging.rb, db/schema.rb, doc/apipie_examples.json, spec/models/other_income_payment_spec.rb, spec/models/outgoings/housing_costs_spec.rb, spec/models/state_benefit_payment_spec.rb, spec/requests/assessments_spec.rb, spec/requests/other_incomes_spec.rb, spec/requests/outgoings_spec.rb, spec/requests/state_benefits_spec.rb, spec/services/decorators/assessment_decorator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1403)
- Added column `client_id` to hold uniquely identifying parameter for client to `outgoings`, `state_benefits` and `other_income_payments` tables
- Updated `OtherIncomesController`, `OutgoingsController` and `StateBenefitsController` to accept option parameter `client_id`
- Updated `AssesmentDecorator` to include remarks in the response
=> AP-1403 populate response with remarks

.circleci/config.yml
AP1370 Set CircleCI Timezone to Europe/London
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1370)
Set the timezone in CircleCi to use Europe/London. This accounts for any GMT to BST (vice versa) changes. As CircleCI was using UTC, which is the same as GMT in Ruby.
Why?
This together fixes the issue of calculating a threshold value that is on the day of the newly introduced values e.g. 06/04/2020 new threshold values were created and placed in a file. 
In the class Threshold under the ".value_for" method 'time < at' compares times. In CircleCI it was comparing BST at 00:00:00 +1 < CircleCI UTC/GMT of 00:00:00 +0, causing old thresholds to be used.
=> AP1370 Set CircleCI Timezone to Europe/London

app/services/remarks.rb, spec/integration/remarks_spec.rb
**BugFix** 
Add old outgoing type names for earlier integration tests spreadsheet
This fixes an error in sentry "_ArgumentError Invalid type: outgoings_childcare_" instead of outgoings_child_care  sent by the master uat branch in Apply
childcare, housing_costs and maintenance type names are retained for compatibility with earlier versions of integration test spreadsheet
Please see in the OutgoingsCreator class under OUTGOING_KLASSES
=> BugFix - Add old outgoing type names for earlier integration tests spreadsheet

app/controllers/other_incomes_controller.rb, app/controllers/outgoings_controller.rb, app/controllers/state_benefits_controller.rb, app/models/concerns/default_client_id.rb, app/models/other_income_payment.rb, app/models/outgoings/base_outgoing.rb, app/models/state_benefit_payment.rb, doc/apipie_examples.json, lib/integration_helpers/deeply_nested_payload_generator.rb, lib/integration_helpers/outgoings_payload_generator.rb, spec/factories/other_income_payment_factory.rb, spec/factories/other_income_source_factory.rb, spec/factories/state_benefit_factory.rb, spec/integration/remarks_spec.rb, spec/integration_helpers/deeply_nested_payload_generator_spec.rb, spec/integration_helpers/outgoings_payload_generator_spec.rb, spec/models/other_income_payment_spec.rb, spec/models/outgoings/housing_costs_spec.rb, spec/models/state_benefit_payment_spec.rb, spec/requests/other_incomes_spec.rb, spec/requests/outgoings_spec.rb, spec/requests/state_benefits_spec.rb, spec/services/creators/other_incomes_creator_spec.rb
AP1405 Transaction id (client_id) is set to mandatory
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1405)
Make client_id a required parameter for: 
1. other_incomes
2. outgoings
3. state_benefits
- Remove DefaultClientId as client_id will have to be passed in as a parameter and therefore defeat the purpose of DefaultClientId.
- Fix integration tests as the spreadsheet does not pass in client_id. By creating a client_id in deeply_nested_payload_generator.rb `#create_client_id` and outgoings_payload_generator.rb
- Update tests with client_id
- **Test deeply_nested_payload_generator to pass test coverage**. This is because the integration tests spreadsheet was not passing a client_id therefore the method …
=> AP1405 Transaction id (client_id) is set to mandatory

app/controllers/applicants_controller.rb, app/controllers/application_controller.rb, app/controllers/assessments_controller.rb, app/controllers/capitals_controller.rb, app/controllers/dependants_controller.rb, app/controllers/other_incomes_controller.rb, app/controllers/outgoings_controller.rb, app/controllers/properties_controller.rb, app/controllers/state_benefits_controller.rb, app/controllers/vehicles_controller.rb, app/services/creators/assessment_creator.rb, app/services/creators/outgoings_creator.rb, doc/apipie_examples.json, spec/requests/applicants_spec.rb, spec/requests/assessments_spec.rb, spec/requests/capitals_spec.rb, spec/requests/dependants_spec.rb, spec/requests/other_incomes_spec.rb, spec/requests/properties_spec.rb, spec/requests/state_benefits_spec.rb, spec/services/creators/assessment_creator_spec.rb
AP1443 Simplify the **POST** responses to the below:
**success response:**
```
{
success: true.
error_messages: [],
}
```
**failure response:**
```
{
success: false.
error_messages: [
'Invalid widget',
'Unknown thing'
]    
}
```
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1443)
- Simplified POST responses to just success and error key/values
- Remove objects key from the POST responses (**except assessments for now**)
**Important notice:** 
For the POST response in assessments, keep it the way it is and include :assessment_id as a key
This means not removing the objects key value until the Apply app no longer uses it.
=> AP1443 simplify response

app/controllers/application_controller.rb, app/services/creators/applicant_creator.rb, app/services/creators/other_incomes_creator.rb, spec/requests/application_controller_spec.rb, spec/services/creators/applicant_creator_spec.rb, spec/services/creators/other_incomes_creator_spec.rb
AP1435 Capture all errors in the application controller
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1435)
Capture all errors in the application controller, reducing the risk of returning a 500 internal server to users of this service.
- Add a `rescue_from StandardError` in the application controller to catch any uncaught errors at the highest level. 
- Add request test for the application controller
- Update creator tests to no longer call Raven.capture_exception as it will be called via the application controller.
----------
I tried and failed to standardise error capturing:
I tried standardising errors using the method stated in this blog [Error Handling in Rails — The Modular Way](https://medium.com/rails-ember-beyond/error-handling-in-rails-the-modular-way-9afcddd2fe1b) but …
=> AP1435 Capture all errors in the application controller

.rubocop.yml, app/services/utilities/payment_period_analyser.rb, spec/integration/ap_1367_spec.rb, spec/services/utilities/payment_period_analyser_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1488)
The code to analyse date frequencies was wildly wrong when recognising weekly frequencies, wrongly identifying almost monthly payments as weekly.  This fixes that.
- replaced code which recognises dates ~ 28 days apart as weekly with code that uses an interval of ~ 7 days
- Wrote a spec to replicate the data we were getting from Mikes test of AP-1367
=> AP-1488 fix weekly frequency bug

app/services/collators/gross_income_collator.rb, spec/services/collators/gross_income_collator_spec.rb
BugFix - Test total gross income in gross income collator.
Test that when irregular student loan and other income student loan both exists then total gross income is taking student loan from other income and not irregular income payments. This is until we remove other income student loan source data.
=> BugFix - Test total gross income in gross income collator

README.md, lib/integration_helpers/deeply_nested_payload_generator.rb, spec/integration_helpers/deeply_nested_payload_generator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1441)
The integration test spreadsheet has been updated so that all transactions in the Other Incomes, Outgoings and State Benefits categories now include a `client_id`.
As a result, the `create_client_id` method in `DeeplyNestedPayloadGenerator` is no longer necessary. This commit removes it and adjusts the logic so that the `client_id` from the spreadsheet is used.
=> AP-1441 Add client id to integration tests

.github/workflows/manual-integration-tests.yml
This _should_ increase the speed of the tests workflow
as it allows caching on all job types not just push
and repository_dispatch was explictly mentioned in the
PR that added it
=> Bump the cache action to v2

app/services/remark_generators/orchestrator.rb, app/services/remark_generators/residual_balance_checker.rb, app/services/remarks.rb, spec/services/remark_generators/orchestrator_spec.rb, spec/services/remark_generators/residual_balance_checker_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1606)
Related to Apply PR https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/1704
If an applicant's assessed capital is above the lower threshold and their current account balance is greater than zero, the application needs to be flagged for caseworker review.
This PR adds a remark generator to identify such cases and add a remark.
=> AP-1606 Add remark generator for residual balances

Gemfile, Gemfile.lock, config/initializers/secure_headers.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1756)
See 4.14 of the security testing report.
Adds the `secure_headers` gem and configures it to generate content-security-policy (CSP) headers. The recommendation was to add this header `Content-Security-Policy: script-src 'self'; object-src 'none'; require-trusted-types-for 'script';` however as CFE is an API-only application I have set it at its most restrictive (ie `'none'` for all) as no scripts/styles/images should ever be loaded.
The suggested `require-trusted-types-for-` element is described in [guidance](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) as 'an experimental API that should not be used in production code' so I have omitted it.
=> AP-1756 Add gem to implement content-security-policy headers

config/initializers/secure_headers.rb
Allow public file sources / resources to be loaded for apipie which wasn't because of the secure_headers csp change
After adding the secure_headers gem, assets from the public file were being blocked by the browser because it was not whitelisted. This has been seen with stylesheets and javascript not being loaded for apipie.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1780)
- Allow origin source to be whitelisted e.g. 'self' this is because we don't gather external resources
-----
-----
=> BUGFIX Allow public file sources to be loaded for apipie

app/controllers/state_benefits_controller.rb, app/services/creators/state_benefits_creator.rb, app/services/remark_generators/multi_benefit_checker.rb, app/services/remark_generators/orchestrator.rb, app/services/remarks.rb, db/migrate/20201019103924_add_flags_to_state_benefit_payment.rb, db/schema.rb, doc/apipie_examples.json, spec/factories/state_benefit_payment_factory.rb, spec/requests/state_benefits_spec.rb, spec/services/remark_generators/multi_benefit_checker_spec.rb, spec/services/remark_generators/orchestrator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1747)
Add a new flagging system that allows Apply to send flagged values to CFE. These can then be parsed and, if required, flag the assessment that is passed back to Apply
This is designed to be extendable, i.e. in the future we can add more values into the `flags` field and check for their presence too
These can then be alerted to case workers when the assessment is returned and processed in Apply.
**NOTE**: this can be merged before the AP-1747 ticket on Apply but may need fixes. 
I am currently testing both ends of the ticket on a local machine but end-to-end testing on UAT may be tricky!
=> AP-1747: multi benefit flagging

app/services/concerns/exemptable.rb, app/services/remark_generators/amount_variation_checker.rb, app/services/remark_generators/base_checker.rb, app/services/remark_generators/frequency_checker.rb, app/services/remark_generators/multi_benefit_checker.rb, spec/integration/ap_1367_spec.rb, spec/services/remark_generators/amount_variation_checker_spec.rb, spec/services/remark_generators/frequency_checker_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1806)
Childcare payments are being flagged for amount variation/frequency issues even if they have been disallowed from the calculation.
This change adds extra checks so that childcare is only flagged if the payments are included in the calculation, which only happens if the applicant is employed or in receipt of a student loan.
=> AP-1806 Fix flagging of childcare payments

app/webpack/packs/application.js
Images had been inadvertantly commented out
Favicon should now load
=> BUGFIX: Update webpack

README.md, app/controllers/assessments_controller.rb, app/models/threshold.rb, app/validators/date_validator.rb, config/application.rb, config/thresholds/28-Jan-2021.yml, spec/services/calculators/property_calculator_spec.rb, spec/validators/date_validator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1869)
1. Add configuration (config/thresholds/28-Jan-2021.yml) for when submission date is on or after 28th January 2021 - the policy change date. 
**To do the above:**
- Remove the mortgage cap by placing its value at 999_999_999_999, which subsequently draws back to using the outstanding mortgage instead of the fixed value of 100_000 in the property calculations.
- Add a new environment variable ALLOW_FUTURE_SUBMISSION_DATE to allow integration tests to run. Otherwise, they will fail because some of our tests in the means spreadsheet has submission dates in the future.
- Use the ALLOW_FUTURE_SUBMISSION_DATE in the date validator to decide whether or not to skip date validation on the submission date. There is :today_or_older …
=> AP-1869 Policy change on property mortgage cap

.github/workflows/manual-integration-tests.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1869)
- Set ALLOW_FUTURE_SUBMISSION_DATE to true for github actions integration tests
=> AP-1869 Update github actions to ALLOW_FUTURE_SUBMISSION_DATE

README.md, app/models/assessment.rb, lib/task_helpers/payload_player.rb, lib/tasks/payload_player.rake
This PR implements a rake task which will play back CFE interaction recorded with the `rake cfe:record_payloads` rake task in the Apply system so that potential bugs can be examined locally.
Usage:
- Copy and paste the output from the Apply `rake cfe:record_payloads` rake task into a file `tmp/api_payloads.yml` in this repo.
- Start a CFE server locally listening on port 4000 `rails s -p 4000`
- Run `rake playback`
This will cause all the requests to be sent to the local instance on 4000 allowing you to examine the records created and/or debug the calculations.
=> Implement API interaction playback rake task

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1895)
- Set the ALLOW_FUTURE_SUBMISSION_DATE env variable in our app circleci config file.
At the moment we have ALLOW_FUTURE_SUBMISSION_DATE set in the circleci project settings on circleci. This PR specifies that we want it set in our app's /circleci/config.yml just for the test container that runs the integration tests.
We set ALLOW_FUTURE_SUBMISSION_DATE to true so that integration tests pass with the means spreadsheet that has submission dates in the future (for future policy change purposes)
=> Place test environment variable in circleci config

app/controllers/explicit_remarks_controller.rb, app/models/assessment.rb, app/models/explicit_remark.rb, app/services/creators/explicit_remarks_creator.rb, app/services/remarks.rb, config/initializers/apipie.rb, config/routes.rb, db/migrate/20201221151158_create_explicit_remarks.rb, db/schema.rb, doc/apipie_examples.json, spec/factories/explicit_remark_factory.rb, spec/integration/ap_1367_spec.rb, spec/integration/remarks_spec.rb, spec/models/assessment_spec.rb, spec/models/explicit_remark_spec.rb, spec/requests/explicit_remarks_spec.rb, spec/services/creators/explicit_remarks_creator_spec.rb, spec/services/remarks_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1928)
Allow client to specify explicit remarks (currently limited to income disregards) which are then included in the assessment result (and will be used by Apply to generate the means report and draw the caseworker's attention to the fact that income disregards have been specified).
- Created:
-  `ExplicitRemarksController`
- `ExplicitRemarksCreationService`
- `ExplicitRemark` model
- Altered the `Remarks` model to take assessment id, and include any explicit remarks in the generation of the assessment result payload.
=> AP-1928 Implement explicit remarks endpoint

.circleci/config.yml, .rubocop.yml, Dockerfile, Gemfile, Gemfile.lock
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1915)
Switches CFE from the `ruby:2.7.2` docker image to the smaller `ruby:2.7.2-alpine3.12` image, also used by Apply, resulting in smaller image sizes and consistent tech stacks.
Image size reduced from 1.34gb to 931mb.
=> AP-1915 - Run CFE on Alpine docker image

app/controllers/application_controller.rb, spec/requests/application_controller_spec.rb
We capture api param errors with an array of string instead of an exception object for simplification, so that user
don't receive the error class in a response.
Solution is to have a seperate Raven.capture_exception when capturing param errors because render_unprocessable is used from child controllers to signify an internal error but without providing error class info etc.
This fixes the below (also found here [sentry](https://sentry.io/organizations/ministryofjustice/issues/2111912118/?project=5404900&query=is%3Aunresolved)):
```
NoMethodError
undefined method `backtrace' for #<Array:0x000055c94d4f9e00>
```
I believe this will stop CFE from sending a 500 error to a consumer (Apply app) and instead send the 422 :unprocessable_entity param error in json format whilst also sending a raven …
=> BugFix Don't send exception object to Raven.capture message

app/services/calculators/pensioner_capital_disregard_calculator.rb, spec/requests/assessments_spec.rb, spec/services/calculators/pensioner_capital_disregard_calculator_spec.rb
Passported applications should have a fixed policy disregard value of 100,000
whilst
Nonpassported application should have a dynamic policy disregard based on threshold values
Make this fix and update tests
=> FIX and update policy disregards

app/services/decorators/assessment_decorator.rb, app/services/decorators/remarks_decorator.rb, spec/integration/policy_disregards_spec.rb, spec/integration/remarks_spec.rb, spec/services/decorators/assessment_decorator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1940)
Add a remarks decorator and use this to determine if policy_disregards remarks should be included in the CFE response.
I have added a test in integration_tests to check that an eligible calculation with policy_disregards remarks is handled correctly. Happy to move this back into remarks_spec.rb but I could not find a clean way to set up 2 different sets of assessment values to trigger the new conditional.
=> Ap 1940 caseworker review

app/controllers/application_controller.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2111)
CFE is crashing instead of formatting a proper error message and sending it to Sentry.  This is the first fix that will format an array of error messages as a string so that Sentry can display it properly.  Then we will be able to see what the cause of the error is and fix that.
=> AP-2111 format error messages instead of crashing

config/thresholds/28-Jan-2021.yml
The copy of rates was taken from a previous year
this caused a regression of the dependant_allowances
=> Bug-fix: dependant-allowances

package.json, yarn.lock
Update two security warnings from dependabot
ssri addresses CVE-2021-27290
is-svg addresses CVE-2021-28092
=> Security: yarn update

Gemfile, Gemfile.lock, spec/rails_helper.rb
This is configured in rails helper but not actually used in the 
codebase (There are no uses of the `with_modified_env` method)
so, rather than update the gem we are removing it!
=> Tech-debt: remove climate-control

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/assessments_controller.rb, config/initializers/raven.rb, config/initializers/sentry.rb, spec/requests/application_controller_spec.rb, spec/requests/assessments_spec.rb, spec/spec_helper.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2057)
This is becasue the old sentry-raven client has entered maintenance mode.
=> AP-2057 Migrate to sentry-ruby from sentry-raven

app/models/proceeding_type_threshold.rb, spec/models/proceeding_type_threshold_spec.rb
Once we switch to V4 of the API, we will need to know whether certain thresholds are waived for a particular proceeding type.
This PR provides the `ProceedingTypeThreshold` class to do that.
If it is one of the thresholds which are subject to a waiver, and if the proceeding type is one where that threshold is waived, then the infinite upper limit of 999,999,999,999 is returned, otherwise Threshold is called to get the normal value.
Call like:
```
ProceedingTypeThreshold.value_for(:DA004, :capital_upper, calculation_date)
```
=> AP-2175 Threshold waiver by proceeding type

config/thresholds/12-Apr-2021.yml, lib/integration_helpers/test_case/result.rb
The mortgage allowance has been accidentally reverted from unlimited to 100,000.  This fixes that
=> Bug fix, revert mortgage allowance to unlimited

app/constants/cfe_constants.rb, app/controllers/assessments_controller.rb, app/models/assessment.rb, app/models/proceeding_type_threshold.rb, app/services/creators/assessment_creator.rb, db/migrate/20210412102115_add_version_proceeding_type_codes.rb, db/schema.rb, spec/models/assessment_spec.rb, spec/requests/assessments_spec.rb, spec/services/calculators/housing_costs_calculator_spec.rb, spec/services/creators/assessment_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2174)
- Added 4 to the list of valid versions
- Expect version to be specified on the first call (to `POST /assessments`).  If not specified, version 3 is assumed.
- Expect payload to have proceeding type ccms codes instead of matter type codes if version 4
- Added version and proceeding type codes to `assessments` table
- Validate the version number, and the new fields on the `Assessment` model
=> AP-2174 Allow version 4 to be specified on POST /assessments

spec/rails_helper.rb, spec/services/collators/childcare_collator_spec.rb
Some unit tests have been written using today's dates, and expecting the values to be caluclated according to the current values in the config files.  When the thresholds and values change, we have to change the expected values in the dates.
This fixes the date for the test so that we don't have to do that every time there is a change to he means test.
=> TESTFIX - fix dates on tests 

.github/workflows/manual-integration-tests.yml
The new ruby runner should read the value from
.ruby-version rather than guessing the latest
ruby version
=> Bug-fix: Update test action

app/services/utilities/calendar_monthly_period_analyser.rb, spec/services/utilities/calendar_monthly_period_analyser_spec.rb
Update the date handling inside CalendarMonthlyPeriodAnalyser
Allow February dates to be handled when the date falls at the end of subsequent months
=> Bug fix/monthly period analyser february

spec/models/gross_income_summary_spec.rb
When run with `bundle exec rspec  --seed 53801` this test would
consistently fail becuase the arrays were slighltly out of sequence
e.g. [a, b, c] == [b, a, c]
Changing to match_array ensures the contents are right and
ignores the sequence
=> Bug-Fix: Update test that failed a match

package.json, yarn.lock
Update package.json to remove warnings around:
CVE-2021-33502
CVE-2021-33587
CVE-2020-28469
CVE-2021-33623
=> Tech-Debt: remove yarn warnings

app/controllers/assessments_controller.rb, spec/factories/assessment_factory.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2452)
This hopefully will cure a flickering spec failure on the assessment request spec
The failures were (shown below) were caused by the capital summary record  **sometimes** not having any eligibility records associated with it, so that the first was nil.   This fix should ensure that eligibility records are always created
```Failures:
1) AssessmentsController GET /assessments/:id no version specified passported has defaulted to using version 3
Failure/Error: expect(parsed_response[:version]).to eq '3'
expected: "3"
got: nil
(compared using ==)
2) AssessmentsController GET /assessments/:id no version specified passported returns capital summary data as json
Failure/Error: expect(parsed_response).to eq(JSON.parse(expected_response, …
```
=> AP-2452 Ensure capital summary gets created with eligibilities

spec/services/calculators/housing_costs_calculator_spec.rb, spec/services/collators/disposable_income_collator_spec.rb
There have been some more flickers of decimal creation and testing and this PR fixes the latest one and attempts to identify and correct any others that may occur in the tests
This issue in `housing_costs_calculator_spec.rb` seems to be caused by changing one side of the equation, the occasional decimal flicker would cause issues with the float comparison.  After running multiple tests, ensuring all values are either comparing decimals with decimals or floats with floats seems to resolve it 🤞 
- There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more …
=> Tech-Debt: Flickering decimal tests

spec/services/legal_framework_api/query_service_spec.rb
Remove Faraday header from webmock spec
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2497)
AP-2497 failed unit tests when merged with main because the version of Faraday didn't match that specified in the specs using webmock.  This change removes the Faraday header from the stubbed response, so that when the Faraday version changes, we don't get failed tests
- You should have looked at the …
=> AP-2497A remove Faraday header from webmock spec

.circleci/config.yml, Gemfile, Gemfile.lock
Test coverage stats aren't being sent to CircleCI so we have a badge that looks like this
To fix this, while running the unit_tests job, configure the code climate test reporter and prepare and upload the results. This required storing the CodeClimate test API key in a CircleCI environment variable named `CC_TEST_REPORTER_ID`
- You should have looked at the diff against master and ensured that nothing …
=> Add CodeClimate to circleci

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2644)
Update references to outdated `circleci/` prefixed docker images
=> AP-2644: Update CircleCI Docker images

.circleci/config.yml
v4.5.1 of the CircleCI Slack Orb is rendering new line symbols (`\n`) in slack message templates. 
This updates to v4.5.2 which resolves this.
=> Bump CircleCI Slack Orb to v4.5.2

deploy/helm/templates/ingress.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2770)
Updates `ingress.yaml` to use `networking.k8s.io/v1` as a result of moving to the live cluster. This reconfigures the ingress using the new syntax.
=> AP-2770 Update ingress.yaml to use networking.k8s.io/v1

docs/pull_request_template.md
Changes outdated references to the `master` branch in the PR template to `main`.
=> Change master to main in PR template

bin/ispec, lib/integration_helpers/test_case/employment_collection.rb, lib/integration_helpers/test_case/worksheet.rb, spec/integration_helpers/test_case/employment_collection_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2820)
Integration tests are run by parsing spreadsheets and submitting the data to CFE and comparing the results with the expected results on the spreadsheet.
The spreadsheets have been expanded to include employment income data, and the PR parses that new data if present and submits it to CFE.  The spreadsheets have not yet been updated to include employment data in the expected results, and this PR does not implement the changes required to parse the extra data in the expected results, which will be done as separate tickets.
- There should be …
=> AP-2820 Parse employment data

lib/integration_helpers/test_case/v4/result_comparer.rb, spec/lib/integration_helpers/test_case/v4/result_comparer_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2820)
The CFE Integration spreadsheets holding test data have can now optionally contain employment income in the data and the expected results.
An earlier PR (also under AP-2820) parsed the data section of the spreadsheet and sent employment data to CFE.
This PR parses the results section of the spreadsheet, and compares the expected employment figures therein with the data returned from CFE.
- The PR description should say what you …
=> AP-2820 Compare new employment figures in actual and expected results

app/controllers/assessments_controller.rb
The MainAssessor was being called twice - both from the MainWorkflow and the AssessmentsController.
This PR removes it from the AssessmentsController
=> Remove unnecessary 2nd call to MainAsssessor

app/controllers/employments_controller.rb, app/services/creators/employments_creator.rb, db/migrate/20220217113523_add_client_id_to_employments.rb, db/schema.rb, doc/apipie_examples.json, spec/requests/employments_controller_spec.rb, spec/services/creators/employments_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2902)
- added `client_id` column to `employments`
- added `client_id` column to `employment_payments`
- accepted option fields `client_id` in payload and stored them to database if present
- You should have checked that the commit …
=> AP-2902 Save client ids in employment payload and save to DB

app/services/collators/disposable_income_collator.rb, app/services/collators/gross_income_collator.rb, spec/services/collators/disposable_income_collator_spec.rb, spec/services/collators/gross_income_collator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-2933)
This pr contains the CFE changes to fix display of CFE results with employment income. The apply changes are in pr https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/3523
It also fixes a bug where EmploymentIncomeMonthlyEquivalentCalculator was not being called.
- The PR description should say what you changed and why, with a …
=> ap-2933 fix display cfe results

docs/CODEOWNERS
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2937)
Fixes https://github.com/ministryofjustice/check-financial-eligibility/issues/766.
Adds a `CODEOWNERS` file requiring all pull requests be approved by a member of the `laa-apply-for-legal-aid` GitHub team.
- You should have checked …
=> AP-2937 Add CODEOWNERS file

app/models/employment.rb, spec/integration/ap_2996_employment_remarks_spec.rb, spec/models/employment_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2996)
Fix issue where amount-variation remarks weren't being generated for employment gross income variations > £60.
=> AP-2996 Fix missing remarks

README.md, app/controllers/employments_controller.rb, db/migrate/20220317185108_make_client_id_mandatory.rb, db/schema.rb, spec/requests/employments_controller_spec.rb, spec/services/creators/employments_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2903)
Make client_id mandatory in the payload
Delete tests that check missing IDs are allowed
Update DB and existing empty fields to state `not-specified`
=> AP-2903 make client_id mandatory

app/services/collators/disposable_income_collator.rb, config/thresholds/2018-04-08.yml, config/thresholds/2019-04-08.yml, config/thresholds/2020-04-06.yml, config/thresholds/2021-01-28.yml, config/thresholds/2021-04-12.yml, config/thresholds/test-jan.yml, spec/services/calculators/income_contribution_calculator_spec.rb, spec/services/calculators/pensioner_capital_disregard_calculator_spec.rb, spec/services/collators/disposable_income_collator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2982)
- Allow negative total disposable incomes
- Amend pensioner_capital_disregard monthly_income_values in threshold files to cater for negative values
- Amend disposable_income_contribution_bands band_zero on threshold files to allow negative values
- You should have looked at the diff against main and ensured that nothing unexpected is included …
=> Ap 2982 show actual disposable income

Gemfile, Gemfile.lock, app/models/employment.rb, app/services/decorators/v4/gross_income_decorator.rb, app/services/utilities/employment_income_monthly_equivalent_calculator.rb, db/migrate/20220330103236_add_tax_monthly_equiv_to_employment_payment.rb, db/schema.rb, spec/factories/employment_factory.rb, spec/models/employment_spec.rb, spec/rails_helper.rb, spec/services/decorators/v4/gross_income_decorator_spec.rb
GGG_EMP_8/9  integration tests still fail due to negative disposable income issue - this is being worked on separately.
[AP-3025](https://dsdmoj.atlassian.net/browse/AP-3025)
To get the [GGG_EMP_8](https://docs.google.com/spreadsheets/d/1fv0oNuQBIB_r2krsRCAM8lOVKdkaf8olbr6Wa-cVEE0/edit#gid=384253371) and [GGG_EMP_9](https://docs.google.com/spreadsheets/d/1fv0oNuQBIB_r2krsRCAM8lOVKdkaf8olbr6Wa-cVEE0/edit#gid=629957388) integration tests passing the `tax` and `national_insurance` for `employment_payments` needs to be converted to calendar monthly amounts. This is inline with the `gross_income` calculation.
- Add `monthly_equiv` columns for `tax` and `national_insurance`
- Update `tax_monthly_equiv` and `national_insurance_monthly_equiv` with values
for calendar month
Before you ask people …
=> [AP-3025] get integration tests GGG_EMP_8/9 passing

app/models/assessment.rb, app/services/creators/assessment_creator.rb, db/migrate/20220421085301_add_assessment_type_to_assessment.rb, db/schema.rb, lib/integration_helpers/test_case/assessment.rb, public/schemas/assessment_request.json, spec/requests/assessments_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-171)
Adds the `assessment_type` to `Assessment` model, and allows creation of it via creator and controller
Adds an integration test for this behaviour on the controller
Adds a check to an existing test to ensure `assessment_type` remains unset if not passed
Partially handles not passing `ccms_codes`, but not completely. That needs some work, but the code in its current state is useful for building other behaviours (POSTs to other endpoints that attach objects to an Assessment) on
=> El-171 - Create crime assessment

app/controllers/dependants_controller.rb, app/services/creators/dependants_creator.rb, doc/apipie_examples.json, spec/factories/dependant_factory.rb, spec/requests/dependants_controller_spec.rb, spec/services/creators/dependants_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-139)
CFE can now accept dependants for a crime assessment.  
- The major change is the relaxing of the validation for `in_full_time_education` in the `DependantsController`.  Validation has instead moved to the model to validate parameter this for civil assessments only.
- You should have looked at the diff against main and ensured that nothing …
=> Dependants for crime assessment now accepted.

.circleci/config.yml, bin/delete_dependabot_deployment, bin/uat_deploy
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2808)
Add delete dependabot script
add section in circle config to call script on dependabot branches
Update uat_deploy to use contexts and the correct env_var, also updated the K8S_NAMESPACE env var in CFE UAT context as this was pointing at staging, now points to uat
- You should have looked at the diff against main and ensured that nothing …
=> AP-2808 add delete script and step to circle config

app/constants/cfe_constants.rb, spec/integration/ap_1367_spec.rb, spec/integration/ap_2996_employment_remarks_spec.rb, spec/integration/policy_disregards_spec.rb, spec/integration/remarks_spec.rb, spec/requests/assessments_controller_spec.rb
This is done because V3 is now deprecated, and with V4 the default it becomes easier to
generate RSWAG documentation for V4
- You should have checked that the commit messages say why the change was …
=> AP-3150 Make V4 the default version

app/constants/cfe_constants.rb, app/services/remark_generators/frequency_checker.rb, app/services/remark_generators/orchestrator.rb, app/services/utilities/employment_income_monthly_equivalent_calculator.rb, spec/factories/employment_factory.rb, spec/services/remark_generators/frequency_checker_spec.rb, spec/services/remark_generators/orchestrator_spec.rb
Extend handling of the remarks when infrequent employment dates are submitted
Ensure the orchestrator checks each job's payments and adds remarks regarding employments_payments/unknown_frequency
=> Update test handling for payment frequency

spec/spec_helper.rb
Enable rspec focused spec running
Thought this had already be configured but looks like not. I, if no
one else, like to use `fdescribe` etc to run certain specs locally.
The check for `ENV['CI']` means it will never run focused specs on circle
(and Github actions I believe).
- You should …
=> Configure rspec focus capabillity

app/services/creators/assessment_creator.rb, app/services/creators/eligibilities_creator.rb, spec/factories/assessment_factory.rb, spec/integration/test_runner_spec.rb, spec/models/assessment_spec.rb, spec/services/creators/assessment_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-171)
Removes the requirement for a proceeding type to be present in crime assessments.
=> Remove the requirement for proceeding type for crime

app/services/decorators/v5/assessment_decorator.rb, app/services/decorators/v5/capital_result_decorator.rb, app/services/decorators/v5/disposable_income_result_decorator.rb, app/services/decorators/v5/gross_income_result_decorator.rb, app/services/decorators/v5/matter_type_result_decorator.rb, app/services/decorators/v5/proceeding_types_result_decorator.rb, app/services/decorators/v5/result_summary_decorator.rb, lib/integration_helpers/test_case/assessment.rb, lib/integration_helpers/test_case/proceeding_type.rb, lib/integration_helpers/test_case/proceeding_types_collection.rb, lib/integration_helpers/test_case/v5/expected_result.rb, lib/integration_helpers/test_case/v5/remarks_comparer.rb, lib/integration_helpers/test_case/v5/result_comparer.rb, lib/integration_helpers/test_case/worksheet.rb, spec/cassettes/IntegrationTests_TestRunner/run_integration_tests/processes_all_the_tests_on_all_the_sheets.yml, spec/integration/test_runner_spec.rb, spec/integration_helpers/test_case/proceeding_type_spec.rb, spec/integration_helpers/test_case/proceeding_types_collection_spec.rb, spec/services/decorators/v5/assessment_decorator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3318)
- Amended integration tests to handle v5 requests (this can be tested by running  bin/ispec -w Fake_HHH_example -vv)
- Added additional v5 decorators to generate v5 responses
NB this pr is based on https://github.com/ministryofjustice/check-financial-eligibility/pull/1005 and can not be merged until that pr has been merged.
- The PR description should say what you changed and why, with a link to the …
=> Ap 3318 changes to integration tests parser v5

app/controllers/outgoings_controller.rb, app/models/outgoings/base_outgoing.rb, app/services/creators/outgoings_creator.rb, app/validators/cfe_date_validator.rb, config/initializers/apipie.rb, public/schemas/outgoings.json.erb, spec/requests/outgoings_controller_spec.rb, spec/requests/swagger_docs/v4/outgoings_spec.rb, spec/requests/swagger_docs/v5/outgoings_spec.rb, spec/services/creators/outgoings_creator_spec.rb, spec/validators/cfe_date_validator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3160)
- amended outgoings controller to use json_schema for validation (and remove APIPIE).
- created a cfe_date_validator for date validations, eventually this will hopefully replace the APIPIE date_validator. Not sure about the naming in the meantime?
- You should have looked at the diff against main and ensured that …
=> ap-3160: convert outgoings controller to use json schema

lib/integration_helpers/test_case/v5/result_comparer.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3360)
This the removes the check for matter types in the V5 response in the specs. (it has been removed now)
=> AP-3360 correction - remove specs for matter type on V5 responses

config/initializers/apipie.rb, spec/requests/capitals_controller_spec.rb, spec/requests/properties_controller_spec.rb
This removes a few APIPIE test generators and removes the names
of updated controllers from the APIPIE about page
=> Fix: Pre APIPIE removal tidy

app/controllers/state_benefit_type_controller.rb, config/initializers/apipie.rb, spec/requests/state_benefit_type_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3162)
This does not need converting to JSON schema as it simplly returns the StateBenefitTypes mapped using as_cfe_json
It removes the apipie `show_in_doc` references and updates the apipie documentation header to remove the reference
- …
=> AP-3162: Remove APIPIE from state_benefit_types

Dockerfile
Add the libxml2-dev and libxslt-dev packages into the docker file, these
are required in the `build.nokogiri --use-system-libraries` step.
Still not sure why it was working before Thursday, but...
=> Fix: Deploying via Circle CI

.github/workflows/manual-integration-tests.yml
These are running silently and no output is produced in the github action 
for the BA to see.
Seems to be because the VERBOSE env var is set to true which translates
to 0 (silent verbosity) in `spec/integration/test_runner_spec.rb`.
- You should have checked that the commit messages say why …
=> Change verbosity of integration tests

config/environments/test.rb, spec/factories/employment_factory.rb, spec/rails_helper.rb
This PR addresses two issues:
1) The eager_loading setting in `/config/test.rb` was set to false.  This means that only those files
actually used during a test run are included in the coverage results.  By setting this to true in the `CI` 
environment variable is set, all files are covered in Circle CI tests, but running tests locally will mean the 
we don't suffer the time hit of loading all files before running a single test.
2) It fixes a flickering test error where employments were being created by the factory as
Job 1, Job 2 etc were being incorrectly sorted (Job 10 coming before Job 9) and therefore
not matching the expected order.  This fixes it by making sure the numerical element is a
four-digit leading zero number (e.g. Job 0010)
[Link to …
=> AP-3108 Ensure code coverage at 100%

app/constants/cfe_constants.rb, app/models/regular_transaction.rb, app/services/concerns/monthly_equivalent_calculatable.rb, public/schemas/regular_transactions.json.erb, spec/requests/swagger_docs/v5/regular_transactions_spec.rb, spec/services/collators/regular_income_collator_spec.rb, spec/services/concerns/monthly_equivalent_calculatable_spec.rb, spec/services/creators/regular_transactions_creator_spec.rb, spec/services/utilities/employment_income_monthly_equivalent_calculator_spec.rb, swagger/v5/swagger.yaml
Add three_monthly equivalent frequency
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3474)
This is required as a design option for
presentation in the Apply service. There
therefore should be a matching frequency in CFE
for consistency and to avoid calculations on
the Apply side.
- …
=> [AP-3474] Enable 3 monthly frequency for regular transactions

.github/workflows/manual-integration-tests.yml
This has been triggered remotely via the slack bot, but that will be turned off for a while.  This alternative should allow users to trigger it via the actions page on github and reduce the need for Devs to run tests for non-dev staff
- You should have checked that the commit messages say …
=> Fix: Allow the test action to be triggered via Github

.github/workflows/manual-integration-tests.yml, bin/ispec, spec/integration/test_runner_spec.rb
Amend integration specs for standard rspec runs
[came out of learnings from AP-3439](https://dsdmoj.atlassian.net/browse/AP-3439)
This allows the integration specs to behave in a more typical fashion
when run directly using rspec - namely, with individual worksheets outputing success
or failure.
examples. to try on branch
```
bundle exec rspec spec/integration/test_runner_spec.rb
OR
bundle exec rspec --format d spec/integration/test_runner_spec.rb
```
But you can continue to use the bin/ispec and its various options
as normal:
```
bin/ispec -r -v -w III_REGTR_1-V5
```
- There should be no unnecessary …
=> Run individual workersheets as separate examples using rspec

app/services/calculators/housing_costs_calculator.rb, spec/services/calculators/housing_costs_calculator_spec.rb, spec/services/collators/housing_costs_collator_spec.rb
Prevent less than zero net housing costs.
[came out of story](https://dsdmoj.atlassian.net/browse/AP-3480)
This closes of an edge case that does not follow
any use case but is technically possible.
BA agreed that in such a situation where housing benefits
are recorded but no housing costs the net housing cost should
, nonetheless, not be below zero.
- You should have looked at the diff against main and …
=> Prevent less than zero for net housing costs

app/constants/cfe_constants.rb, app/models/gross_income_summary.rb, app/models/regular_transaction.rb, app/services/calculators/housing_costs_calculator.rb, app/services/collators/housing_costs_collator.rb, app/services/workflows/non_passported_workflow.rb, lib/integration_helpers/test_case/regular_transaction.rb, public/schemas/regular_transactions.json.erb, spec/lib/integration_helpers/test_case/regular_transaction_spec.rb, spec/models/regular_transaction_spec.rb, spec/requests/swagger_docs/v5/regular_transactions_spec.rb, spec/services/calculators/housing_costs_calculator_spec.rb, spec/services/collators/housing_costs_collator_spec.rb, spec/services/collators/regular_income_collator_spec.rb, swagger/v5/swagger.yaml
Calcuate net housing costs for non passported regular transactions workflow
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3480)
net housing costs = housing payments - housing benefits. This must be added to disposable_income_summary
to obtain an accurate CFE result.
**Detail**
When calculating gross and net housing costs relevant
regular transaction records must also be considered.
This can be summarised as:
- #gross_housing_costs should be the sum of any applicable*
outgoings (a.k.a bank transactions), cash transactions
and regular transactions.
- #monthly_housing_benefit should be the sum of applicable** #state_benefits
plus regular transactions
- #net_housing_costs can be uncapped or capped (based on having dependants)
and is usually gross, less benefits.
_\* applicable …
=> [AP-3480] Calculate net_housing_costs for regular transactions

app/controllers/assessments_controller.rb, app/services/workflows/main_workflow.rb, spec/requests/assessments_controller_spec.rb, spec/services/workflows/main_workflow_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3946)
=> AP-3496 Return error payload instead of raising an exception

spec/integration/test_runner_spec.rb
Do not force refresh on rspec suite runt
Stale worksheets will be refreshed anyway.
=> Do not force refresh on integration test worksheets on rspec run

package.json, yarn.lock
The package terser before 4.8.1, from 5.0.0 and before 5.14.2 are vulnerable to Regular Expression Denial of Service (ReDoS) due to insecure usage of regular expressions.
**References**
https://github.com/advisories/GHSA-4wf5-vphf-c2xc
https://github.com/terser/terser/blob/master/lib/compress/evaluate.js%23L135
https://snyk.io/vuln/SNYK-JS-TERSER-2806366
- You should have looked at the diff against main …
=> [Security] Selectively bump terser to 5.15.0

public/schemas/regular_transactions.json.erb, spec/requests/regular_transactions_controller_spec.rb, spec/requests/swagger_docs/v5/regular_transactions_spec.rb, spec/services/creators/regular_transactions_creator_spec.rb, swagger/v5/swagger.yaml
Remove minItem 1 validation from schema for regular_transactions
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3451)
Other endpoints and creator services allow for and handle an empty
payload items from Apply. The `RegularTransactionsCreator` already
does too.
This validation raised errors on testing via Apply as empty payload
items are sent, inline with other endpoints.
There is a related ticket [AP-3511](https://dsdmoj.atlassian.net/browse/AP-3511) I have
raised to question whether we should actually be doing this.
- There should be no unnecessary whitespace changes. These make diffs harder …
=> [AP-3451] Remove minItem schema validation for regular transactions

README.md
Update readme regarding intgeration test changes
previous pr changed the way the integration tests run when run as part of the
rspec suite as opposed to ispec.
=> Update readme regarding intgeration test changes

spec/integration/v5_full_assessment_spec.rb
Add CFE intgration tests for disposable income summary
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3516)
Extend plain rspec integration tests rather than rely purely
on worksheet tests:
We should be using these CFE integration tests to cover overall
results more extensively, as a separate set of testing to the
Worksheet based integration tests. The latter are more intended
for use by the BA to setup scenarios.
This adds two tests, one to test existing disposable income
result for a prexexisting tests requests. This is to provide
a regression and comparison for the second test, which uses
the regular transaction mechanism to add income, outgoings
and husing benefits.
The second test uses the exact equivalent values of the
the first test's request but supplied via the regular …
=> [AP-3516] extend integration tests

app/views/layouts/apipie_override.html.erb
Add lang attribte to html tag
See [sonarcloud bug](https://sonarcloud.io/component_measures?metric=reliability_rating&selected=ministryofjustice_check-financial-eligibility%3Aapp%2Fviews%2Flayouts%2Fapipie_override.html.erb&view=list&id=ministryofjustice_check-financial-eligibility)
The <html> element should provide the lang and/or xml:lang attribute in order to identify the default language of a document.
It enables assistive technologies, such as screen readers, to provide a comfortable reading experience by adapting the pronunciation and accent to the language. It also helps braille translation software, telling it to switch the control codes for accented characters for instance.
- Github …
=> Add lang attribute to html tag

app/models/applicant.rb, app/models/dependant.rb, config/locales/activerecord.yml, spec/models/applicant_spec.rb, spec/models/dependant_spec.rb
This replaces the custom validation with the default `validates` method using the `comparison` key.
Dependants and Applicants  with a date of birth in the future are invalid.
Tests have also been added.
=> Validate date_of_birth using `:comparison`

app/models/applicant.rb, spec/models/applicant_spec.rb
The `#age_at_submission` method was not used anywhere, so it has been removed.
=> Remove redundant Applicant method

app/constants/cfe_constants.rb, app/models/gross_income_summary.rb, app/models/irregular_income_payment.rb, app/services/base_workflow_service.rb, app/services/collators/childcare_collator.rb, app/services/collators/gross_income_collator.rb, app/services/decorators/v5/gross_income_decorator.rb, app/services/decorators/v5/gross_income_summary_decorator.rb, db/migrate/20221014131213_add_unspecified_source_income_to_gross_income_summaries.rb, db/schema.rb, public/schemas/irregular_incomes.json.erb, spec/integration/policy_disregards_spec.rb, spec/integration/v5_full_assessment_spec.rb, spec/requests/irregular_incomes_controller_spec.rb, spec/services/assessors/gross_income_assessor_spec.rb, spec/services/collators/gross_income_collator_spec.rb, spec/services/collators/regular_income_collator_spec.rb, spec/services/creators/irregular_income_creator_spec.rb, spec/services/decorators/v5/gross_income_decorator_spec.rb, spec/services/decorators/v5/gross_income_summary_decorator_spec.rb, swagger/v5/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/EL-400)
We want to capture income that is from an unspecified source, expressed by the user as a single total figure received over the past 3 months. By 'unspecified source' we mean income that doesn't fall under any of the named types of regular or irregular payments that CFE accepts, with no requirement on the user to describe the source in any way.
So this PR adds 'unspecified_source_income' as a valid irregular type, and 'quarterly' as a valid income frequency, to the irregular payments model/endpoint.
Also, because prior to this there was only one irregular payment type - student loans - there was a bit of logic that assumed all irregular payments were student loans, an assumption that started to break with the new type. So I …
=> EL-400: Allow 'unspecified_source_income'/'quarterly' irregular payment type

Gemfile, Gemfile.lock
Throughout the application, we are using the [Faraday gem] to make requests to the Legal Framework API.
Until now, we have been relying on Faraday being pulled in by another of our dependencies.
Ideally we would be using [Net::HTTP] since it comes as part of Ruby, but at the very least we should be explicit about the dependencies our application needs.
[Faraday gem]: https://github.com/lostisland/faraday
[Net::HTTP]: https://rubyapi.org/3.1/o/net/http
=> Define Faraday gem as an explicit dependency

spec/integration/v5_full_assessment_spec.rb
This fixes a [flaky spec].
The expectation asserted that the nested arrays in the response contained strings in a specific order, but this wasn't guaranteed to always be the case.
The order-agnostic `contain_exactly` matcher is preferred instead.
[flaky spec]: https://app.circleci.com/pipelines/github/ministryofjustice/check-financial-eligibility/6112/workflows/f7608ecd-e2ad-4232-8dc0-e350105b3aed/jobs/21133/tests
=> Fix flaky integration spec

app/models/dependant.rb, app/services/collators/childcare_collator.rb, app/services/decorators/v5/applicant_decorator.rb, db/migrate/20221026151032_add_employed_to_applicants.rb, db/schema.rb, public/schemas/applicant_v5.json.erb, spec/models/dependant_spec.rb, spec/services/collators/childcare_collator_spec.rb, spec/services/decorators/v5/applicant_decorator_spec.rb
Before, employed applicants with child dependants were never able to receive the
child care cost allowance they were eligible for.
This was because the `#applicant_employed?` method in the childcare collator
always returned false.
Now that the method has been implemented, employed applicants that are eligible
will receive the correct child care cost allowance.
The applicant schema now defines an optional boolean employed attribute that
consumers can use to specify an applicant's employed status.
=> Employed applicants with dependants receive child care allowance

public/schemas/applicant_v5.json.erb, spec/requests/applicants_controller_spec.rb
Allow null employed attribute values
This is probably not preferable to a fix in
the consumer to ensure nil/null is sent as
false, however passported applicants may
be either employed or not and we may 
not need to know.
Fixes: [sentry error](https://sentry.io/organizations/ministryofjustice/issues/3710598017/?project=5416054&referrer=slack)
- You should have looked at the diff against main and ensured …
=> Allow null employed attribute values

app/models/capital_item.rb, app/models/capital_summary.rb, app/models/property.rb, app/models/vehicle.rb, app/services/calculators/subject_matter_of_dispute_disregard_calculator.rb, app/services/collators/capital_collator.rb, app/services/creators/capitals_creator.rb, app/services/decorators/v5/capital_result_decorator.rb, app/services/decorators/v5/capital_summary_decorator.rb, config/thresholds/2021-04-12.yml, config/thresholds/2022-04-11.yml, db/migrate/20221027150350_add_smod_to_capital_items.rb, db/schema.rb, public/schemas/capital.json.erb, public/schemas/properties.json.erb, public/schemas/vehicles.json.erb, spec/factories/capital_item_factory.rb, spec/factories/property_factory.rb, spec/factories/vehicle_factory.rb, spec/integration/v5_full_assessment_spec.rb, spec/requests/swagger_docs/v5/capitals_spec.rb, spec/requests/swagger_docs/v5/properties_spec.rb, spec/requests/swagger_docs/v5/vehicles_spec.rb, spec/services/calculators/subject_matter_of_dispute_disregard_calculator_spec.rb, spec/services/collators/capital_collator_spec.rb, spec/services/creators/capitals_creator_spec.rb, spec/services/creators/properties_creator_spec.rb, spec/services/decorators/v5/capital_result_decorator_spec.rb, spec/services/decorators/v5/capital_summary_decorator_spec.rb, swagger/v5/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/EL-428)
'Subject matter of dispute' is an additional capital disregard that works somewhat similarly to the pensioner disregard. The requirement is for the disposable capital calculated result to disregard all assets that are marked as "subject matter of dispute", UP TO a threshold that is currently set at £100,000.00. Any disputed asset value above that threshold is included in the disposable capital calculation.
To that end, this PR adds the following:
- API additional optional fields to tell CFE when capital items, properties and vehicles are the subject matter of dispute
- Logic to disregard assets up to the SMOD disregard threshold from the disposable capital calculation
- SMOD disregard summary in result payload
=> EL-428: Acknowledge and account for SMOD assets

app/constants/cfe_constants.rb
This was added to seeds in LFA but not added as an allowed
type in CFE.
[Came out of UAT on story](https://dsdmoj.atlassian.net/browse/AP-3489)
Add missing section 8 proceeding type to list of those allowed
by CFE.
- You should have checked that the commit messages say why the change was …
=> Add SE007 to list of valid procceding types

app/services/collators/childcare_collator.rb, app/services/collators/regular_outgoings_collator.rb, app/services/concerns/childcare_eligibility.rb, lib/integration_helpers/test_case/applicant.rb, spec/factories/dependant_factory.rb, spec/services/collators/regular_outgoings_collator_spec.rb
Fix missing child care eligibility logic for regular transactions
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3632)
Prevent regular transactions of the child care category
from incrementing/decrementing totals and `_all_sources` inline
with similar behaviour for bank and cash transactions.
This was an omission of required logic identified by
EFE team. It should have been handled as part of the
regular transaction implementation.
Child care costs (outgoings) should only ever be applied
if the applicant has dependants under 16 AND is employed
or is a student (receiving a student loan).
5 new integration worksheet tests have been added to exercise child care scenarios, These can be found on 
this [spreadsheet](https://docs.google.com/spreadsheets/d/1WHg-BrR263L3SxWMrzxS_2Xvo6eM8tAU …
=> Fix for child care eligibility rules with regular transaction

.github/workflows/delete-uat-release.yml
Bump github action for delete-uat-release from v1.0.0 to use v1.0.1
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3669)
handles deprecated set-output command
[delete uat release GHA v1.0.1](https://github.com/ministryofjustice/laa-civil-apply-delete-uat-release/releases/tag/v1.0.1)
see [github action bump PR](https://github.com/ministryofjustice/laa-civil-apply-delete-uat-release/pull/2) for more details.
see [successful test deletion with no deprecation warnings](https://github.com/ministryofjustice/legal-framework-api/actions/runs/3582656827/jobs/6027140022)
- There should be no unnecessary …
=> Bump delete-uat-release from v1.0.0 to v1.0.1

.github/dependabot.yml
We don't use the `sentry-raven` gem anymore, so we don't need to ignore it anymore.
=> Remove redundant dependabot ignore rule

spec/factories/dependant_factory.rb
In tests "aged 15" dependents had a date of birth set to a range that included 16 years before the submission date, meaning their 16th birthday was on the submission date, meaning for the purposes of the calculation they were 16. This was causing approximately 1 test run in every 366 to fail.
This PR fixes the off-by-one error, and also adjusts the other age traits to use all valid date of birth values for those ages.
Thanks to the EFE team
- The PR description should say what you changed …
=> Fix: remove test flakiness

.circleci/config.yml, config/environments/test.rb
Before, the code was eager loaded every time a test was run.
When you're running a single test, this doesn't make much sense.
This updates the test configuration to eager load only when the `CI` environment
variable is set (i.e default Rails behaviour).
=> Only eager load Ruby code when running tests in CI

.github/workflows/brakeman-analysis.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker-image-scan.yaml, .github/workflows/manual-integration-tests.yml
This PR:
* Updates all CodeQL actions to v2 as v1 is due to be deprecated on Jan 18th 2023
* Updates all checkout actions to v3 as v2 uses node12 which has also been deprecated
=> Fix: Update the github action versions

.circleci/config.yml
Rename cluster cert var
For clarity as there is only one cluster certificate regardless
of namespace. tidy up following circleci incident
**Have added the new var, will delete the old var assuming deploy goes out to production ok**
- You should have checked that the commit messages say why …
=> Rename cluster cert var

.github/workflows/brakeman-analysis.yml
This updates the brakeman analysis workflow to use the reusable brakeman workflow in
[@ministryofjustice/laa-reusable-github-actions](https://github.com/ministryofjustice/laa-reusable-github-actions).
=> Use reusable Brakeman GitHub Action

.github/workflows/brakeman-analysis.yml
The workflow incorrectly specified `pull_requent` as its trigger...
=> Fix typo in Brakeman scan GitHub Action

public/schemas/common.json, public/schemas/vehicles.json.erb, spec/requests/swagger_docs/v5/vehicles_spec.rb
Add nullable_currency field type to allow nil values for currency fields
Set `loan_amount_outstanding` to this field type for validation
Update vehicles rspec to test a nil value for this field
- You should have checked that the …
=> AP-3786 add nullable currency field type

app/models/concerns/monthly_equivalent_calculator.rb, spec/services/calculators/housing_costs_calculator_spec.rb
The EFE team have identified an edge case where the frequency changing causes the calculator to return
incorrect results
=> Fix: MonthlyEquivalentCalculator bug

config/thresholds/2023-04-10.yml, config/thresholds/values.yml, spec/services/calculators/dependant_allowance_calculator_spec.rb
From 10th April 2023, changes to means assessment fixed allowances for dependants will go live.
This updates the dependant allowances to the new amounts. All other thresholds have been left unchanged.
There is an allowance for dependant partners, but this hasn't been captured since we expect to integrate with the new `CFE-Civil` service before releasing partner means functionality in Apply.
These allowances should be applied for applications with submission dates on or after 2023-04-10.
Apply handles the logic surrounding application submission dates and delegated functions.
The Apply service passes the submission date when making requests to the assessment endpoint, so we do not need to worry about calculating it for an application.
[Link to …
=> Update dependant allowances
