ministryofjustice/check-financial-eligibility

.circleci/config.yml

Add tests to CircleCi process

---

docs/pull_request_template.md

adds a docs folder and pull request template same as the one used in Apply

Add a pull request template to the repo

---

Gemfile
Gemfile.lock
app/services/monthly_salary_calculator.rb
app/services/time_series_calculator.rb
spec/services/monthly_salary_calculator_spec.rb
spec/services/time_series_calculator_spec.rb
spec/support/salary_pattern_generator.rb

[Jira AP-640](https://dsdmoj.atlassian.net/browse/AP-640)
Takes a time series of salary data, and returns the monthly equivalent based on some simple logic:
- if payment weekly or two-weekly: average
- if payment monthly and difference more than 60: average
- if payment monthly and difference less than 60: latest entry
I've assumed the four weekly payments would also be averaged.
The code also includes a time series calculator which includes tools that allows for some analysis of the time periods, and could be used to check patterns match the given time period. This was created when it seemed likely that we would not know the period types, and therefore have to determine them.

AP 640 convert salary values to monthly

---

app/models/applicant.rb
app/services/base_workflow_service.rb
app/services/legacy_base_workflow_service.rb
app/services/workflow_predicate/below_lower_capital_threshold_predicate.rb
app/services/workflow_service/disposable_capital_assessment.rb
app/services/workflow_service/not_self_employed.rb
app/services/workflow_service/passported.rb
app/services/workflow_service/self_employed.rb
spec/factories/applicant_factory.rb
spec/services/base_workflow_spec.rb
spec/services/capitals_creation_service_spec.rb
spec/services/payment_period_analyser_spec.rb
spec/services/workflow_predicate/determine_passported_spec.rb
spec/services/workflow_predicate/determine_self_employed_spec.rb
spec/spec_helper.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-820)
This predicate always returns false, so just change the test to pass in an Assessment object

AP-820 Convert DetermineSelfEmployed predicate to use database

---

app/controllers/properties_controller.rb
app/services/properties_creation_service.rb
doc/apipie_examples.json
spec/requests/properties_spec.rb
spec/services/properties_creation_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-770)
Update the properties controller to use APIPIE

Ap 770 convert properties controller

---

app/controllers/applicants_controller.rb
app/controllers/capitals_controller.rb
app/controllers/dependants_controller.rb
app/controllers/incomes_controller.rb
app/controllers/properties_controller.rb
app/controllers/vehicles_controller.rb
app/services/applicant_creation_service.rb
app/services/capitals_creation_service.rb
app/services/dependants_creation_service.rb
app/services/income_creation_service.rb
app/services/integration_tests/service_client.rb
app/services/integration_tests/use_case_runner.rb
app/services/integration_tests/worksheet_parser.rb
app/services/properties_creation_service.rb
app/services/vehicle_creation_service.rb
spec/requests/applicants_spec.rb
spec/requests/capitals_spec.rb
spec/requests/dependants_spec.rb
spec/requests/properties_spec.rb
spec/services/applicant_creation_service_spec.rb
spec/services/capitals_creation_service_spec.rb
spec/services/dependants_creation_service_spec.rb
spec/services/income_creation_service_spec.rb
spec/services/integration_tests/worksheet_parser_spec.rb
spec/services/properties_creation_service_spec.rb
spec/services/vehicle_creation_service_spec.rb

Refactor controllers to get assessment_id from URL rather than body.
Plus a few other small changes.

Refactor controllers to get assessment_id from URL rather than body

---

README.md
spec/services/integration_tests/test_runner_spec.rb
spec/services/integration_tests/worksheet_parser_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-992)
- In verbose mode, displayed which cases passed, and which cases failed 
- Added instructions to the readme about how to run the integration tests
- Created three more tickets off the back of the failing tests

AP-992 Tidy up

---

LICENCE.md

Adds the MIT licence to the repo to make it open source as per MOJ guidelines
https://ministryofjustice.github.io/technical-guidance/standards/licencing-software-or-code/#each-repository-should-include-a-licence-file

Add MIT licence to repo

---

.gitignore
Gemfile
Gemfile.lock
app/models/state_benefit_type.rb
db/migrate/20191202153330_create_state_benefit_types.rb
db/schema.rb
db/seeds.rb
db/seeds/data/state_benefit_types.yml

Categorise benefits as included/excluded
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-638)
This is moving the benefit types code from the Apply for legal aid app into this app
- Create State Benefit Types model
- Create Yaml file including seeds of the benefit types.
- Create database seed for Benefit Types including whether or not they're included or excluded in this check financial eligibilty test.
- Add dibber gem to help with seeding data

AP638 Categorise benefits as included/excluded

---

.circleci/config.yml
app/controllers/state_benefits_controller.rb
app/models/gross_income_summary.rb
app/models/state_benefit.rb
app/models/state_benefit_payment.rb
app/models/state_benefit_type.rb
app/services/state_benefits_creation_service.rb
config/routes.rb
db/migrate/20191209134932_create_state_benefits.rb
db/migrate/20191209161655_create_state_benefit_payments.rb
db/migrate/20191211101351_change_state_benefit_type_name.rb
db/schema.rb
db/seeds/data/state_benefit_types.yml
doc/apipie_examples.json
spec/factories/state_benefit_type.rb
spec/models/state_benefit_spec.rb
spec/requests/state_benefits_spec.rb

State benefits endpoint
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1100)
Add StateBenefit model and migration file
Add StateBenefitPayment model and migration file
Add StateBenefitsCreationService, which will save the state benefits and payments into the state benefit table using methods on the StateBenefit model.
Update StateBenefitType column from :description to :name
Add spec test for state benefit model and request
Add factory for state benefit type
Update APIPIE documentation
Important:
Edit circleci config to not use db:setup for testing as it seeds the database. Instead to use db:create db:schema:load , which stops the database from being seeded as part of circleci tests.
To note:
If it's a unknown …

AP1100 State benefits endpoint

---

app/services/assessors/gross_income_assessor.rb
app/services/base_workflow_service.rb
app/services/collators/gross_income_collator.rb
db/migrate/20191220085420_drop_statuses.rb
db/schema.rb
spec/services/assessors/gross_income_assessor_spec.rb
spec/services/collators/gross_income_collator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1134)
- Updated `Collators::GrossIncomeCollator` to  write total monthly income to `GrossIncomeSummary` record
- New class `Assessors::GrossIncomeAssessor` to write result of comparison against threshold to `GrossIncomeSummary` record
- Dropped unused statuses table

AP-1134 Gross income assessment

---

.circleci/config.yml
Dockerfile
Gemfile.lock
app/models/assessment.rb
app/models/disposable_income_summary.rb
app/models/other_income_source.rb
app/services/base_workflow_service.rb
app/services/collators/childcare_collator.rb
spec/factories/assessment_factory.rb
spec/factories/disposable_income_summary_factory.rb
spec/services/collators/childcare_collator_spec.rb

Class to collect all childcare outgoing payments, determine whether or not the applicant
is eligible for them to be discounted from his gross income, and then write the monthly
equivalent value to the dipsoable income summary record.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1150)

AP-1150 Childcare collator class

---

app/models/concerns/monthly_equivalent_calculator.rb
app/models/gross_income_summary.rb
app/models/outgoings/housing_cost.rb
app/models/state_benefit_type.rb
app/services/collators/housing_costs_collator.rb
db/migrate/20200102101936_refactor_disposable_income_summaries.rb
db/schema.rb
spec/factories/disposable_income_summary_factory.rb
spec/factories/outgoing_factory.rb
spec/models/gross_income_summary_spec.rb
spec/models/outgoings/housing_costs_spec.rb
spec/services/collators/housing_cost_collator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1050)
- renamed `monthly_housing_costs` on `DisposableIncomeSummary` to `monthly_gross_housing_costs`
- added field `monthly_net_housing_costs` to `DisposableIncomeSummary`
- added field `monthly_housing_benefit` to `DisposableIncomeSummary`
- added method 'allowable_amount` to `Outgoings::HousingCost` to return the amount adjusted depending on the type of housing cost
- Wrote collator to calculate the monthly equivalent of the allowable housing cost, the monthly equivalent of the housing benefit and write the net housing benefit to the `DisposableIncomeSummary` record

AP-1151 Housing costs collator

---

app/models/disposable_income_summary.rb
app/services/collators/maintenance_collator.rb
spec/services/collators/maintenance_collator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1154)

AP-1154 Maintenance collator

---

LICENCE.md

Updates the copyright licence for this year

Update year in licence file

---

.rubocop.yml
app/services/calculators/dependant_allowance_calculator.rb
app/services/collators/dependants_allowance_collator.rb
config/thresholds/8-Apr-2018.yml
config/thresholds/8-Apr-2019.yml
config/thresholds/8-Apr-2020.yml
db/migrate/20200103110430_add_dependant_allowance_to_dependants.rb
db/schema.rb
spec/factories/dependant_factory.rb
spec/services/assessors/property_assessor_spec.rb
spec/services/assessors/vehicle_assessor_spec.rb
spec/services/calculators/dependant_allowance_calculator_spec.rb
spec/services/collators/dependants_allowance_collator_spec.rb
spec/services/creators/capitals_creator_spec.rb
spec/services/utilities/payment_period_analyser_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1152)
- Added `dependant_allowance` field to `Dependant`
- Added `monthly_dependants_allowance` field to `DisposableIncomeSummary`
- Created `Calculators::DependantsAllowanceCalculator` to determine allowance for each dependant
- Created `Collators::DependantAllowanceCollator` to call the calculator for each dependant and update the dependant records with the result, and write the sum of the results to the `DisposableIncomeSummary` record.

AP-1152 Dependants collator

---

app/models/disposable_income_summary.rb
app/services/assessors/disposable_income_assessor.rb
app/services/calculators/income_contribution_calculator.rb
config/thresholds/8-Apr-2018.yml
config/thresholds/8-Apr-2019.yml
config/thresholds/8-Apr-2020.yml
db/migrate/20200106120428_add_income_contribution_to_disposableincome_summary.rb
db/schema.rb
spec/services/assessors/disposable_income_assessor_spec.rb
spec/services/calculators/income_contribution_calculator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1166)
This class is run after all the component parts have been done and the `DisposableIncomeSummary` record has been populated.
- Created `Assessors::DisposableIncomeAssessor` to determine result
- Created `Calculators::IncomeContributionCalculator` to determine contribution if assessment result is `eligible_with_contribution`

AP-1166 Assess disposable income and calculate contribution (if any)

---

app/controllers/state_benefit_type_controller.rb
app/models/state_benefit_type.rb
config/routes.rb
doc/apipie_examples.json
spec/requests/state_benefit_types_spec.rb

Expose State Benefit Type endpoint to return all types
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1322)
Add state benefit type GET route to return all state benefit types values for name, label and dwpcode.
Add a controller and request tests
IMPORTANT:
Updated the apipie for a GET request, which if the first for this application.

Expose State Benefit Type endpoint to return all types

---

Gemfile.lock
doc/apipie_examples.json
spec/factories/state_benefit_type_factory.rb
spec/requests/state_benefit_types_spec.rb

Update Documentation for StateBenefitType
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1322)
Updated the documentation to show an example of the API request for getting all state benefit types
Updated the state benefit type factory to have a random dwp_code value

Update Documentation for StateBenefitType

---

.github/workflows/manual-integration-tests.yml

The workflow for running integrated tests needed to reference the secrets stored in github

Fix the workflow

---

app/models/state_benefit_type.rb
db/migrate/20200430131555_add_category_to_state_benefit_types.rb
db/migrate/20200430145529_seed_state_benefit_categories.rb
db/migration_helpers/category_seeder.rb
db/schema.rb
db/seeds.rb
db/seeds/data/state_benefit_types.yml
doc/apipie_examples.json
spec/factories/state_benefit_type_factory.rb
spec/models/state_benefit_type_spec.rb
spec/requests/state_benefit_types_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1396)
- added new column `category` to `StateBenefitType` model
- Added migration to seed new column
- Added the following two fields to the JSON output:
- `exclude_from_gross_income`
- `category`

AP-1396 Expose new fields on State Benefit Types

---

.rubocop.yml
app/models/threshold.rb
app/services/decorators/assessment_decorator.rb
app/services/decorators/result_decorator.rb
app/services/remarks.rb
spec/services/remarks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1400)
Created `Remarks` class with methods to easily add in remarks.

AP-1400 Create Remarks class

---

.circleci/config.yml

* switch to executors, it's a new pattern and slightly nicer to read
where setup and steps differ
* review which image was used for each step - some steps were loading
way more than needed and this slowed down some steps,
e.g. installing and running postgres to build and push to ECR
* remove linespaces between steps, they were inconsistent
* refine the workflows, at a good time of day, add_branch now completes
in ~4-5 minutes
* remove potential blockers in the merge_pr flow
Replicate this back into the apply steps... especially ensuring the correct executor is used for the job

Refine the CircleCI for CFE

---

README.md
app/controllers/assessments_controller.rb
app/services/creators/assessment_creator.rb
doc/apipie_examples.json
spec/integration/remarks_spec.rb
spec/integration/test_runner_spec.rb
spec/requests/assessments_spec.rb
spec/services/creators/assessment_creator_spec.rb

AP154 Update assessments post response
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1454)
- Remove the :objects key and its values in the POST response on Assessments as it is no longer needed.
- Return the below in the Assessment POST response
```
{
success: success?,
assessment_id: new_assessment.id,
errors: errors
}
```
- Update documentation
- Update tests
**Extra**:
- Add a banner to show if CFE master is passing in the README

AP154 Update assessments post response

---

app/services/collators/disposable_income_collator.rb
spec/services/collators/disposable_income_collator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1472)
Added legal_aid payments to the outgoings and deductions calculation

Ap 1472 calc error

---

app/controllers/irregular_incomes_controller.rb
app/models/gross_income_summary.rb
app/models/irregular_income_payment.rb
app/models/other_income_source.rb
app/services/base_workflow_service.rb
app/services/collators/childcare_collator.rb
app/services/collators/gross_income_collator.rb
app/services/creators/irregular_income_creator.rb
app/services/decorators/gross_income_summary_decorator.rb
app/services/decorators/irregular_income_payments_decorator.rb
app/services/decorators/monthly_income_equivalent_decorator.rb
config/routes.rb
db/migrate/20200611165619_add_monthly_student_loan_to_gross_income_summary.rb
db/migrate/20200612123146_create_irregular_income_payments.rb
db/schema.rb
doc/apipie_examples.json
spec/factories/gross_income_summary_factory.rb
spec/factories/irregular_income_payment_factory.rb
spec/factories/other_income_source_factory.rb
spec/integration/remarks_spec.rb
spec/models/irregular_income_payment_spec.rb
spec/requests/irregular_incomes_spec.rb
spec/services/assessors/gross_income_assessor_spec.rb
spec/services/collators/childcare_collator_spec.rb
spec/services/collators/gross_income_collator_spec.rb
spec/services/creators/irregular_income_creator_spec.rb
spec/services/decorators/gross_income_summary_decorator_spec.rb
spec/services/decorators/irregular_income_payments_decorator_spec.rb
spec/services/decorators/monthly_income_equivalent_decorator_spec.rb

AP1464 Add irregular income endpoint
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1464)
- Create an IrregularIncomePayment model and table
- Add index to irregular_income_payments table to make sure income_type has one type e.g. student_loan per gross_income_summary
- GrossIncomeSummary has many IrregularIncomePayment
- Add a new field called :monthly_student_loan on the gross_income_summaries table.
- Add IrregularIncomeCreator to create irregular_income_payments
- Update ChildcareCollator to use either other income source or irregular_income_payments for student loans
- Update GrossIncomeCollator to update :monthly_student_loan on the gross income summary. It's set to zero, if there is no irregular_income_payments
- Update **GrossIncomeSummaryDecorator** to include …

AP1464 Add irregular income endpoint

---

app/controllers/irregular_incomes_controller.rb
config/initializers/apipie.rb
config/routes.rb
doc/apipie_examples.json
spec/integration/test_runner_spec.rb
spec/requests/irregular_incomes_spec.rb

update the irregular_income endpoint to match the others and what was expected in Apply:
* pluralise the endpoint 
* update the documentation
* update the tests

Fix: pluralise other incomes

---

app/models/other_income_source.rb
app/services/collators/childcare_collator.rb
app/services/decorators/gross_income_summary_decorator.rb
spec/factories/gross_income_summary_factory.rb
spec/factories/other_income_source_factory.rb
spec/integration/ap_1367_spec.rb
spec/integration/remarks_spec.rb
spec/requests/other_incomes_spec.rb
spec/services/collators/childcare_collator_spec.rb
spec/services/collators/gross_income_collator_spec.rb
spec/services/creators/other_incomes_creator_spec.rb
spec/services/decorators/gross_income_summary_decorator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1468)
remove all references to student_loan as an option for 'other_incomes'

remove student_loan from other_incomes

---

.github/workflows/manual-integration-tests.yml

This allows slack to send the username that triggered the job which will allow me to chase people if there are failures and try and fix them! 😃 

Fix: Add a debug statement

---

README.md

~[Link to story](https://dsdmoj.atlassian.net/browse/AP-XXX)~
Add a link to the architecture diagram for CFE as well as the source. There's an extra whitespace removal at the end, apologies. Happy to remove it if preferred!

Add architecture diagram to README

---

app/controllers/explicit_remarks_controller.rb
doc/apipie_examples.json
spec/factories/explicit_remark_factory.rb
spec/integration/remarks_spec.rb
spec/models/explicit_remark_spec.rb
spec/requests/explicit_remarks_spec.rb
spec/services/creators/explicit_remarks_creator_spec.rb
spec/services/remarks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1932)
They are called policy disregards in apply, so change here for consistency.

AP-1932 Change all references of income_disreards to policy_disregards

---

README.md

Updates the readme to provide information about how to run the `pry-rescue` gem.

Update readme to add pry-rescue details

---

README.md
app/controllers/capitals_controller.rb
spec/requests/capitals_spec.rb

Remove non-negative validation for capital

---

app/constants/cfe_constants.rb
app/controllers/api/statuses_controller.rb
app/controllers/assessments_controller.rb
app/models/assessment.rb
app/models/cash_transaction.rb
app/models/cash_transaction_category.rb
app/models/gross_income_summary.rb
app/models/other_income_source.rb
app/services/collators/gross_income_collator.rb
app/services/creators/cash_transactions_creator.rb
app/services/decorators/assessment_decorator.rb
app/services/decorators/gross_income_summary_decorator.rb
app/services/decorators/monthly_income_equivalent_decorator.rb
app/services/decorators/other_income_source_decorator.rb
db/migrate/20210122165708_add_bank_cash_transactions_to_gross_income_summary.rb
db/schema.rb
spec/factories/assessment_factory.rb
spec/factories/cash_transaction_category_factory.rb
spec/factories/cash_transaction_factory.rb
spec/factories/gross_income_summary_factory.rb
spec/factories/other_income_source_factory.rb
spec/models/assessment_spec.rb
spec/requests/assessments_spec.rb
spec/services/collators/gross_income_collator_spec.rb
spec/services/decorators/gross_income_summary_decorator_spec.rb
spec/services/decorators/other_income_source_decorator_spec.rb

[https://dsdmoj.atlassian.net/browse/AP-1979](https://dsdmoj.atlassian.net/browse/AP-1979)
Added new fields for the gross summary income

AP-1979: Add new fields to gross income summary with ability to call assessment version 3

---

spec/services/collators/capital_collator_spec.rb

Fix tests post removal of mortgage cap

---

README.md
app/controllers/assessments_controller.rb
doc/apipie_examples.json
spec/requests/assessments_spec.rb

Update apidocs with assessment V3 response example data

---

Gemfile
Gemfile.lock
app/controllers/assessments_controller.rb
doc/apipie_examples.json
spec/requests/assessments_spec.rb
spec/spec_helper.rb
spec/support/apipie_helper.rb

Add titles to apipie tests to differentiate between different examples

---

Dockerfile
Gemfile
Gemfile.lock
README.md
spec/spec_helper.rb

Update readme badges

---

app/models/gross_income_summary.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-2159)
Add partially_eligible to the results options to fix an error made visible by ap-2159

Bugfix error on ap-2159

---

.circleci/config.yml
.github/workflows/brakeman-analysis.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-2454)
Update CI calls from master -> main

AP-2454: Update default branch references

---

app/models/employment.rb
app/models/employment_payment.rb
db/migrate/20211110163830_add_gross_earned_income_to_gross_income_summary.rb
db/migrate/20211110164414_create_employments.rb
db/migrate/20211110164710_create_employment_payments.rb
db/schema.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-2665)

AP-2665 Create employments and employment_payments tables and models

---

bin/uat_deploy

Correct ingress identifier in uat deploy script. This will allow work on ap-2632 to proceed.

Correct ingress identifier in uat deploy script

---

.circleci/config.yml
app/controllers/employments_controller.rb
app/models/assessment.rb
app/services/creators/employments_creator.rb
config/initializers/apipie.rb
config/routes.rb
doc/apipie_examples.json
spec/requests/employments_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-2667)

Ap 2667 employment endpoint

---

doc/apipie_examples.json
spec/requests/assessments_spec.rb

I noticed that assessments was lacking the example for the POST  this adds it to show on  /apidocs

add missing examples

---

spec/services/calculators/employment_income_calculator_spec.rb

Change a test so that it doesn't fail on CirclCI.
Tested locally, before the change it failed 2 times in 20 runs. After the change there were no failures in 20 runs.
I chose 0.001 as this will be a tenth of one pence, so it should be small enough that it will not change the usefulness of the test.
- You should have looked at the diff against master and ensured that nothing unexpected is included in …

Fix flaky test

---

app/services/collators/disposable_income_collator.rb
app/services/collators/gross_income_collator.rb
spec/factories/assessment_factory.rb
spec/factories/employment_factory.rb
spec/factories/employment_payment_factory.rb
spec/factories/gross_income_summary_factory.rb
spec/services/collators/disposable_income_collator_spec.rb
spec/services/collators/gross_income_collator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-2671)
Call employment_income_calculator on non-passported workflow.

Call employment income calculator on non-passported workflow

---

.circleci/config.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-2604)
Updated circileci config to use circleci/slack@4.5.1 orb (https://circleci.com/developer/orbs/orb/circleci/slack?version=4.5.1).

ap-2604: update circleci orb to 4.5.1

---

.github/workflows/codeql-analysis.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-2694)
Adds a GitHub Action to run CodeQL.

AP-2694 Add CodeQL

---

Guardfile

The same pattern works well on Apply but has started failing here
re-initialise and update

TechDebt: Update guardfile

---

lib/integration_helpers/test_case/employment_collection.rb
spec/integration_helpers/test_case/employment_collection_spec.rb

A PR from before the rubocop-govuk gem was merged, this updates the
codebase to allow deployments to continue

Fix: Rubocop mis-match

---

.rubocop_todo.yml
app/constants/cfe_constants.rb
app/models/cash_transaction.rb
app/validators/currency_validator.rb
config/initializers/sentry.rb
lib/task_helpers/payload_player.rb
spec/integration/policy_disregards_spec.rb
spec/support/salary_pattern_generator.rb
spec/support/shared_examples.rb

Fix GOV.UK Rubocop offences:
- RSpec/NotToNot
- RSpec/Rails/HttpStatus 
- Rails/TimeZone 
- Style/Lambda
- Style/RedundantFreeze

Fix GOV.UK Rubocop offences

---

.rubocop_todo.yml
spec/factories/state_benefit_type_factory.rb
spec/integration/ap_1367_spec.rb
spec/integration/policy_disregards_spec.rb
spec/integration/test_runner_spec.rb
spec/models/other_income_source_spec.rb
spec/services/assessors/disposable_income_assessor_spec.rb
spec/services/collators/capital_collator_spec.rb
spec/services/collators/dependants_allowance_collator_spec.rb
spec/services/collators/gross_income_collator_spec.rb
spec/services/creators/assessment_creator_spec.rb
spec/services/decorators/v3/assessment_decorator_spec.rb
spec/services/decorators/v3/deductions_decorator_spec.rb
spec/services/decorators/v4/assessment_decorator_spec.rb
spec/services/utilities/payment_period_analyser_spec.rb
spec/services/workflows/passported_workflow_spec.rb

More rubocop fixes to get into GOVUK standard

---

.rubocop_todo.yml
db/migration_helpers/category_seeder.rb
db/seeds.rb

Fix GOV.UK Rubocop Rails/Output offences

Fix GOV.UK Rubocop Rails/Output offences

---

.rubocop_todo.yml
spec/models/bank_holiday_spec.rb
spec/models/other_income_source_spec.rb
spec/services/collators/capital_collator_spec.rb
spec/services/collators/dependants_allowance_collator_spec.rb
spec/services/decorators/v3/assessment_decorator_spec.rb
spec/services/decorators/v3/capital_summary_decorator_spec.rb
spec/services/decorators/v3/gross_income_summary_decorator_spec.rb
spec/services/decorators/v4/assessment_decorator_spec.rb
spec/services/legal_framework_api/response_error_spec.rb
spec/services/workflows/self_employed_workflow_spec.rb

Fix GOV.UK Rubocop RSpec/VerifiedDoubles offences

Fix GOV.UK Rubocop RSpec/VerifiedDoubles offences

---

config/environments/test.rb
config/thresholds/2018-04-08.yml
config/thresholds/2019-04-08.yml
config/thresholds/2020-04-06.yml
config/thresholds/2021-01-28.yml
config/thresholds/test-jan.yml
db/schema.rb
lib/integration_helpers/test_case/employment_collection.rb
lib/integration_helpers/test_case/v4/expected_result.rb
lib/integration_helpers/test_case/v4/remarks_comparer.rb
lib/integration_helpers/test_case/v4/result_comparer.rb
spec/integration_helpers/test_case/employment_collection_spec.rb
spec/lib/integration_helpers/test_case/v4/remarks_comparer_spec.rb
spec/lib/integration_helpers/test_case/v4/result_comparer_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-2914)
Add client_id to both the employment and employment_payments sections of the CFE results
Check remarks actual vs expected

Ap 2914 emp integration tests

---

.rubocop.yml
.rubocop_todo.yml
Gemfile.lock
app/services/creators/applicant_creator.rb
app/services/creators/capitals_creator.rb
app/services/creators/cash_transactions_creator.rb
app/services/creators/dependants_creator.rb
app/services/creators/employments_creator.rb
app/services/creators/explicit_remarks_creator.rb
app/services/creators/irregular_income_creator.rb
app/services/creators/other_incomes_creator.rb
app/services/creators/properties_creator.rb
app/services/creators/state_benefits_creator.rb
app/services/creators/vehicle_creator.rb
spec/models/assessment_spec.rb
spec/models/eligibility/gross_income_spec.rb

Fix remaining GOVUK rubocop issues

---

Gemfile
Gemfile.lock

Update apipie-rails gem to version 0.6.0

Update apipie-rails gem to version 0.6.0

---

app/controllers/assessments_controller.rb
doc/apipie_examples.json
spec/requests/assessments_controller_spec.rb

[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-2934)
- Removed references to v3 from assessments_controller.rb
- Removed show_in_doc for v3 in assessments_controller_spec
- Regenerated apidocs by running APIPIE_RECORD=examples bundle exec rspec
- You should have looked at the diff against main and ensured …

ap-2934: update api docs

---

app/services/collators/gross_income_collator.rb

Adds a comment to clarify the process for calculating the total_gross_income, specifically we start with the monthly_student_loan and then add income to this value.

clarify process for calculation in comment

---

config/thresholds/2022-04-11.yml
config/thresholds/values.yml
spec/services/calculators/dependant_allowance_calculator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3001)
Add new threshold file
Update tests to cover either side of the new thresholds
Added new tests to the CFE integration tests

Ap 3001 threshold changes

---

config/thresholds/2022-04-11.yml
spec/services/calculators/dependant_allowance_calculator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3001)
Increase threshold post 11/04/2022 for child aged 15
Missed in previous updates.

Fix threshold post 11/04/2022 for children aged 15

---

app/controllers/application_controller.rb
app/models/request_log.rb
db/migrate/20220429103502_create_requests_table.rb
db/schema.rb

This PR is the first step to getting to the bottom of what is causing the delays.
It logs all request timings (by means of an Around Filter on Application Controller) to record
the details of the request and how long it took to serve.
- You should have looked at the diff against main and ensured that nothing …

AP-3067 Investigate slow CFE responses

---

spec/factories/assessment_factory.rb
spec/requests/assessments_controller_spec.rb
spec/requests/employments_controller_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/EL-139)
- Added request spec to EmploymentsControllerSpec for criminal Employment data.
- Added trait to AssessmentFactory for assessment of type criminal.

Eligibility/el 139/employment record

---

.circleci/config.yml
lib/tasks/rswag.rake

Check for unapplied swagger documentations changes
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3136)
Devs may make changes to rswag specs but forget to run `rake rswag:specs:swaggerize`
to update the `swagger.yaml` files that the documentation pages are rendered from.
- You should …

Add swaggerize test

---

.github/workflows/delete-uat-release.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3184)
Shared github action across all apply teams
repos for performing this common task

[AP-3184] Add github action to delete UAT release

---

app/controllers/capitals_controller.rb
app/models/capital_item.rb
app/services/creators/capitals_creator.rb
config/initializers/apipie.rb
public/schemas/capital.json.erb
public/schemas/common.json
spec/requests/capitals_controller_spec.rb
spec/requests/swagger_docs/v4/capitals_spec.rb
spec/services/creators/capitals_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-3153)
This is part of the project to remove APIPIE from CFE and replace it with RSWAG.  
APIPIE carries out a lot of validation of the incoming payload, which RSWAG does not, so we are going to use JSON schema to perform that validation.
This PR focuses on the Capitals Controller.
- You …

Ap 3153 capitals controller to json

---

app/controllers/dependants_controller.rb
app/services/creators/dependants_creator.rb
config/initializers/apipie.rb
public/schemas/dependants.json.erb
spec/requests/dependants_controller_spec.rb
spec/requests/swagger_docs/v4/dependants_spec.rb
spec/services/creators/dependants_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3155)

ap-3155: Remove apipie from dependants controller

---

app/controllers/cash_transactions_controller.rb
app/services/creators/cash_transactions_creator.rb
public/schemas/cash_transaction.json.erb
public/schemas/common.json
spec/requests/cash_transactions_controller_spec.rb
spec/requests/swagger_docs/v4/cash_transactions_spec.rb
spec/services/creators/cash_transactions_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-3154)
AP-3154 This is part of the project to remove APIPIE from CFE and replace it with RSWAG.
APIPIE carries out a lot of validation of the incoming payload, which RSWAG does not, so we are going to use JSON schema to perform that validation.
This commit focuses on the Cash Transactions Controller.
- The PR description should say what you changed and why, with a link to the JIRA …

AP-3154 Cash transactions controller to JSON Schema

---

app/controllers/properties_controller.rb
app/services/creators/properties_creator.rb
config/initializers/apipie.rb
doc/apipie_examples.json
public/schemas/common.json
public/schemas/properties.json.erb
spec/requests/properties_controller_spec.rb
spec/requests/swagger_docs/v4/properties_spec.rb
spec/services/creators/properties_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3161)

Remove apipie from properties controller

---

app/controllers/other_incomes_controller.rb
app/services/creators/other_incomes_creator.rb
config/initializers/apipie.rb
public/schemas/other_incomes.json.erb
spec/requests/other_incomes_controller_spec.rb
spec/requests/swagger_docs/v4/other_incomes_spec.rb
spec/services/creators/other_incomes_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3159)

Remove APIPIE from other_incomes controller

---

app/controllers/employments_controller.rb
app/services/creators/employments_creator.rb
config/initializers/apipie.rb
public/schemas/employment.json.erb
spec/integration/ap_2996_employment_remarks_spec.rb
spec/requests/employments_controller_spec.rb
spec/requests/swagger_docs/v4/employments_spec.rb
spec/services/creators/employments_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-3156)
This is part of the project to remove APIPIE from CFE and replace it with RSWAG.
APIPIE carries out a lot of validation of the incoming payload, which RSWAG does not, so we are going to use JSON schema to perform that validation.
This work focuses on the Employments Controller.
- You …

AP-3156 Employments controller to JSON Schema

---

app/controllers/cash_transactions_controller.rb
app/services/creators/cash_transactions_creator.rb
public/schemas/cash_transaction.json.erb
public/schemas/common.json
spec/requests/cash_transactions_controller_spec.rb
spec/services/creators/cash_transactions_creator_spec.rb

This is part of the project to remove APIPIE from CFE and replace it with RSWAG.
Amend Cash Transactions controller to bring it inline with other controllers.

Amend Cash Transactions controller

---

app/models/capital_item.rb
app/services/creators/capitals_creator.rb
public/schemas/capital.json.erb
public/schemas/cash_transaction.json.erb
spec/requests/capitals_controller_spec.rb
spec/requests/swagger_docs/v4/capitals_spec.rb

This is part of the project to remove APIPIE from CFE and replace it with RSWAG.
Amend Capitals and Cash Transactions controllers to bring inline with other controllers.

Amend Capitals and Cash Controllers

---

app/controllers/assessments_controller.rb
app/services/creators/assessment_creator.rb
public/schemas/assessment.json.erb
spec/requests/assessments_controller_spec.rb
spec/requests/swagger_docs/v3/assessments_spec.rb
spec/requests/swagger_docs/v4/assessments_spec.rb
spec/services/creators/assessment_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3165)

ap-3165: convert asessments_controller to use json_schema

---

app/services/creators/applicant_creator.rb
public/schemas/applicant_v5.json.erb
spec/requests/applicants_controller_spec.rb
spec/requests/swagger_docs/v5/applicants_spec.rb
swagger/v5/swagger.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3341)

ap-3441: remove involvement_type from applicant for v5 assessments

---

app/controllers/state_benefits_controller.rb
app/models/state_benefit_payment.rb
app/services/creators/state_benefits_creator.rb
config/initializers/apipie.rb
public/schemas/state_benefits.json.erb
spec/requests/state_benefits_controller_spec.rb
spec/requests/swagger_docs/v4/state_benefits_spec.rb
spec/requests/swagger_docs/v5/state_benefits_spec.rb
spec/services/creators/state_benefits_creator_spec.rb

and remove apipie
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3163)

ap-3163: covert state_benefits_controller to use json_schema

---

app/controllers/irregular_incomes_controller.rb
app/services/creators/irregular_income_creator.rb
public/schemas/irregular_incomes.json.erb
spec/requests/irregular_incomes_controller_spec.rb
spec/requests/swagger_docs/v4/irregular_incomes_spec.rb
spec/requests/swagger_docs/v5/irregular_incomes_spec.rb
spec/services/creators/irregular_income_creator_spec.rb
swagger/v4/swagger.yaml

AP-3158 add JSON schema validation to irregular incomes

---

README.md

To run the tests locally the following env var is required:
LEGAL_FRAMEWORK_API_HOST
This adds it to the list on the readme so a new user knows that it is required

Update README to include required envvar

---

app/controllers/vehicles_controller.rb
app/models/vehicle.rb
app/services/creators/vehicle_creator.rb
app/validators/cfe_date_validator.rb
public/schemas/vehicles.json.erb
spec/requests/outgoings_controller_spec.rb
spec/requests/swagger_docs/v4/vehicles_spec.rb
spec/requests/swagger_docs/v5/vehicles_spec.rb
spec/requests/vehicles_controller_spec.rb
spec/services/creators/state_benefits_creator_spec.rb
spec/services/creators/vehicle_creation_service_spec.rb
spec/validators/cfe_date_validator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3164)
Removed apipie from vehicles_controller
Converted vehicles_controller to validate using json_schema, similar to other controllers
Fixed a bug with cfe_date_validator and increased test coverage
- You should have checked that the …

Ap 3164 convert vehicles controller json schema

---

.github/workflows/docker-image-scan.yaml

Add snyk docker image scanning
Warn about docker image vulnerabilities so we can patch them

Add snyk docker image scanning

---

app/models/employment.rb
spec/models/employment_spec.rb

An [existing bug resurfaced recently][sentry].
When an assessment has an employment but the employment has no employment payments, a `NoMethodError` is raised when calculating the range of monthly employment income payments in `Utilities::EmploymentIncomeVariationChecker`.
While this scenario is unlikely, it is possible —so we should account for it.
In the instance linked above, the applicant specified that they were not employed, but the HMRC response indicated that the applicant had an employment (albeit they had no employment payments).
This change ensures the most recent employment payment is only used for monthly employment values when there is at least one employment payment, and the range of employment income payments is below the threshold.
If there are no employment payments or …

Fix employment without payments bug

---

.github/workflows/brakeman-analysis.yml

Update setup ruby to use non-deprecated version?
This is unclear as the suggested version says to use the current version!

Fix: Update brakeman action

---

spec/spec_helper.rb

Minor fix to Update VCR filtering.
Fix to prior PR: https://github.com/ministryofjustice/check-financial-eligibility/pull/1261

Update VCR filtering

---

.github/workflows/docker-image-scan.yaml

This updates the `docker-image-scan.yml` GitHub Action workflow 
to use the reusable `snyk.yml` workflow to scan docker images.

Use reusable snyk workflow to scan docker images

---

app/controllers/main_controller.rb
config/routes.rb
spec/requests/main_controller_spec.rb

Root to api-docs
Convenience for devs and others.

Root to api-docs

---

public/schemas/common.json
public/schemas/vehicles.json.erb
spec/requests/swagger_docs/v5/vehicles_spec.rb

Reverts ministryofjustice/check-financial-eligibility#1304

Revert "AP-3786 add nullable currency field type"

---

.circleci/config.yml

Use the cloud platform executor and tidy the job
e.g. packages are not required

Fix: Update circle build-and-push job

---

Gemfile.lock

Reverts ministryofjustice/check-financial-eligibility#1440
```
Errors
Fetch error
Internal Se

Revert "build(deps): bump rswag-api from 2.9.0 to 2.10.1"
